{"text": "It is better to be hated for what you are than to be loved for what you are not.", "author": "André Gide", "tags": ["life", "love"], "born_date": "November 22, 1869", "born_location": "in Paris, France", "desciption": "André Paul Guillaume Gide was a French author and winner of the Nobel Prize in literature in 1947. G"}
{"text": "It is our choices, Harry, that show what we truly are, far more than our abilities.", "author": "J.K. Rowling", "tags": ["abilities", "choices"], "born_date": "July 31, 1965", "born_location": "in Yate, South Gloucestershire, England, The United Kingdom", "desciption": "See also: Robert GalbraithAlthough she writes under the pen name J.K. Rowling, pronounced like rolli"}
{"text": "The person, be it gentleman or lady, who has not pleasure in a good novel, must be intolerably stupid.", "author": "Jane Austen", "tags": ["aliteracy", "books", "classic", "humor"], "born_date": "December 16, 1775", "born_location": "in Steventon Rectory, Hampshire, The United Kingdom", "desciption": "Jane Austen was an English novelist whose works of romantic fiction, set among the landed gentry, ea"}
{"text": "A day without sunshine is like, you know, night.", "author": "Steve Martin", "tags": ["humor", "obvious", "simile"], "born_date": "August 14, 1945", "born_location": "in Waco, Texas, The United States", "desciption": "Stephen Glenn \"Steve\" Martin is an American actor, comedian, writer, playwright, producer, musician,"}
{"text": "A woman is like a tea bag; you never know how strong it is until it's in hot water.", "author": "Eleanor Roosevelt", "tags": ["misattributed-eleanor-roosevelt"], "born_date": "October 11, 1884", "born_location": "in The United States", "desciption": "Anna Eleanor Roosevelt was an American political leader who used her influence as an active First La"}
{"text": "I have not failed. I've just found 10,000 ways that won't work.", "author": "Thomas A. Edison", "tags": ["edison", "failure", "inspirational", "paraphrased"], "born_date": "February 11, 1847", "born_location": "in Milan, Ohio, The United States", "desciption": "Thomas Alva Edison was an American inventor, scientist and businessman who developed many devices th"}
{"text": "The world as we have created it is a process of our thinking. It cannot be changed without changing our thinking.", "author": "Albert Einstein", "tags": ["change", "deep-thoughts", "thinking", "world"], "born_date": "March 14, 1879", "born_location": "in Ulm, Germany", "desciption": "In 1879, Albert Einstein was born in Ulm, Germany. He completed his Ph.D. at the University of Zuric"}
{"text": "Imperfection is beauty, madness is genius and it's better to be absolutely ridiculous than absolutely boring.", "author": "Marilyn Monroe", "tags": ["be-yourself", "inspirational"], "born_date": "June 01, 1926", "born_location": "in The United States", "desciption": "Marilyn Monroe (born Norma Jeane Mortenson; June 1, 1926 – August 5, 1962) was an American actress, "}
{"text": "Life is what happens to us while we are making other plans.", "author": "Allen Saunders", "tags": ["fate", "life", "misattributed-john-lennon", "planning", "plans"], "born_date": "April 24, 1899", "born_location": "in The United States", "desciption": "Allen Saunders was an American writer, journalist and cartoonist who wrote the comic strips Steve Ro"}
{"text": "Good friends, good books, and a sleepy conscience: this is the ideal life.", "author": "Mark Twain", "tags": ["books", "contentment", "friends", "friendship", "life"], "born_date": "November 30, 1835", "born_location": "in Florida, Missouri, The United States", "desciption": "Samuel Langhorne Clemens, better known by his pen name Mark Twain, was an American author and humori"}
{"text": "It is not a lack of love, but a lack of friendship that makes unhappy marriages.", "author": "Friedrich Nietzsche", "tags": ["friendship", "lack-of-friendship", "lack-of-love", "love", "marriage", "unhappy-marriage"], "born_date": "October 15, 1844", "born_location": "in Röcken bei Lützen, Prussian Province of Saxony, Germany", "desciption": "Friedrich Wilhelm Nietzsche (1844–1900) is a German philosopher of the late 19th century who challen"}
{"text": "The opposite of love is not hate, it's indifference. The opposite of art is not ugliness, it's indifference. The opposite of faith is not heresy, it's indifference. And the opposite of life is not death, it's indifference.", "author": "Elie Wiesel", "tags": ["activism", "apathy", "hate", "indifference", "inspirational", "love", "opposite", "philosophy"], "born_date": "September 30, 1928", "born_location": "in Sighet, Romania", "desciption": "Eliezer Wiesel was a Romania-born American novelist, political activist, and Holocaust survivor of H"}
{"text": "I may not have gone where I intended to go, but I think I have ended up where I needed to be.", "author": "Douglas Adams", "tags": ["life", "navigation"], "born_date": "March 11, 1952", "born_location": "in Cambridge, England, The United Kingdom", "desciption": "Douglas Noël Adams was an English author, comic radio dramatist, and musician. He is best known as t"}
{"text": "I like nonsense, it wakes up the brain cells. Fantasy is a necessary ingredient in living.", "author": "Dr. Seuss", "tags": ["fantasy"], "born_date": "March 02, 1904", "born_location": "in Springfield, MA, The United States", "desciption": "Theodor Seuss Geisel was born 2 March 1904 in Springfield, MA. He graduated Dartmouth College in 192"}
{"text": "You may not be her first, her last, or her only. She loved before she may love again. But if she loves you now, what else matters? She's not perfect—you aren't either, and the two of you may never be perfect together but if she can make you laugh, cause you to think twice, and admit to being human and making mistakes, hold onto her and give her the most you can. She may not be thinking about you every second of the day, but she will give you a part of her that she knows you can break—her heart. So don't hurt her, don't change her, don't analyze and don't expect more than she can give. Smile when she makes you happy, let her know when she makes you mad, and miss her when she's not there.", "author": "Bob Marley", "tags": ["love"], "born_date": "February 06, 1945", "born_location": "in Nine Mile, Saint Ann, Jamaica", "desciption": "Robert \"Bob\" Nesta Marley OM was a Jamaican singer, songwriter, guitarist, and activist. He was the "}
{"text": "Beauty is in the eye of the beholder and it may be necessary from time to time to give a stupid or misinformed beholder a black eye.", "author": "Jim Henson", "tags": ["humor"], "born_date": "September 24, 1936", "born_location": "in Greenville, Mississippi, The United States", "desciption": "James Maury \"Jim\" Henson was the most widely known puppeteer in American television history. He was "}
{"text": "Anyone who thinks sitting in church can make you a Christian must also think that sitting in a garage can make you a car.", "author": "Garrison Keillor", "tags": ["humor", "religion"], "born_date": "August 07, 1942", "born_location": "in Anoka, Minnesota, The United States", "desciption": "Garrison Keillor (born Gary Edward Keillor on August 7, 1942 in Anoka, Minnesota) is an American aut"}
{"text": "If you judge people, you have no time to love them.", "author": "Mother Teresa", "tags": ["attributed-no-source"], "born_date": "August 26, 1910", "born_location": "in Skopje, Macedonia, the Former Yugoslav Republic of", "desciption": "Blessed Teresa of Calcutta, or Mother Teresa, born Agnes Gonxha Bojaxhiu was an Albanian Roman Catho"}
{"text": "For every minute you are angry you lose sixty seconds of happiness.", "author": "Ralph Waldo Emerson", "tags": ["happiness"], "born_date": "May 25, 1803", "born_location": "in Boston, Massachusetts, The United States", "desciption": "in 1803, Ralph Waldo Emerson was born in Boston. Educated at Harvard and the Cambridge Divinity Scho"}
{"text": "We read to know we're not alone.", "author": "William Nicholson", "tags": ["misattributed-to-c-s-lewis", "reading"], "born_date": "January 12, 1948", "born_location": "in Lewes, Sussex, The United Kingdom", "desciption": "Librarian Note: There is more than one author in the GoodReads database with this name. See this thr"}
{"text": "All you need is love. But a little chocolate now and then doesn't hurt.", "author": "Charles M. Schulz", "tags": ["chocolate", "food", "humor"], "born_date": "November 26, 1922", "born_location": "in Minneapolis, MN, The United States", "desciption": "Charles Monroe Schulz was an American cartoonist, whose comic strip Peanuts proved one of the most p"}
{"text": "I love you without knowing how, or when, or from where. I love you simply, without problems or pride: I love you in this way because I do not know any other way of loving but this, in which there is no I or you, so intimate that your hand upon my chest is my hand, so intimate that when I fall asleep your eyes close.", "author": "Pablo Neruda", "tags": ["love", "poetry"], "born_date": "July 12, 1904", "born_location": "in Parral, Chile", "desciption": "Pablo Neruda was the pen name and, later, legal name of the Chilean writer and politician Neftalí Ri"}
{"text": "I have always imagined that Paradise will be a kind of library.", "author": "Jorge Luis Borges", "tags": ["books", "library"], "born_date": "August 24, 1899", "born_location": "in Buenos Aires, Argentina", "desciption": "Jorge Francisco Isidoro Luis Borges Acevedo (Spanish pronunciation: [xoɾxe lwis boɾxes], Russian: Хо"}
{"text": "It is never too late to be what you might have been.", "author": "George Eliot", "tags": ["inspirational"], "born_date": "November 22, 1819", "born_location": "in South Farm, Arbury Hall, Nuneaton, Warwickshire, The United Kingdom", "desciption": "In 1819, novelist George Eliot (nee Mary Ann Evans), was born at a farmstead in Nuneaton, Warwickshi"}
{"text": "Love does not begin and end the way we seem to think it does. Love is a battle, love is a war; love is a growing up.", "author": "James Baldwin", "tags": ["love"], "born_date": "August 02, 1924", "born_location": "in Harlem, New York, The United States", "desciption": "Librarian Note: There is more than one author in the GoodReads database with this name. See this thr"}
{"text": "Only in the darkness can you see the stars.", "author": "Martin Luther King Jr.", "tags": ["hope", "inspirational"], "born_date": "January 15, 1929", "born_location": "in Atlanta, Georgia, The United States", "desciption": "Martin Luther King, Jr. was one of the pivotal leaders of the American civil rights movement. King w"}
{"text": "You can never get a cup of tea large enough or a book long enough to suit me.", "author": "C.S. Lewis", "tags": ["books", "inspirational", "reading", "tea"], "born_date": "November 29, 1898", "born_location": "in Belfast, Ireland", "desciption": "CLIVE STAPLES LEWIS (1898–1963) was one of the intellectual giants of the twentieth century and argu"}
{"text": "A reader lives a thousand lives before he dies, said Jojen. The man who never reads lives only one.", "author": "George R.R. Martin", "tags": ["read", "readers", "reading", "reading-books"], "born_date": "September 20, 1948", "born_location": "in Bayonne, New Jersey, The United States", "desciption": "George R. R. Martin was born September 20, 1948, in Bayonne, New Jersey. His father was Raymond Coll"}
{"text": "There is no friend as loyal as a book.", "author": "Ernest Hemingway", "tags": ["books", "friends", "novelist-quotes"], "born_date": "July 21, 1899", "born_location": "in Oak Park, Illinois, The United States", "desciption": "Ernest Miller Hemingway was an American author and journalist. His economical and understated style "}
{"text": "Life isn't about finding yourself. Life is about creating yourself.", "author": "George Bernard Shaw", "tags": ["inspirational", "life", "yourself"], "born_date": "July 26, 1856", "born_location": "in Dublin, Ireland", "desciption": "George Bernard Shaw was an Irish playwright, socialist, and a co-founder of the London School of Eco"}
{"text": "He's like a drug for you, Bella.", "author": "Stephenie Meyer", "tags": ["drug", "romance", "simile"], "born_date": "December 24, 1973", "born_location": "in Connecticut, The United States", "desciption": "I was born in Connecticut in 1973, during a brief blip in my family's otherwise western U.S. existen"}
{"text": "The difference between genius and stupidity is: genius has its limits.", "author": "Alexandre Dumas fils", "tags": ["misattributed-to-einstein"], "born_date": "July 27, 1824", "born_location": "in Paris, France", "desciption": "Alexandre Dumas (son) was born in Paris, France, the illegitimate child of Marie-Laure-Catherine Lab"}
{"text": "If you only read the books that everyone else is reading, you can only think what everyone else is thinking.", "author": "Haruki Murakami", "tags": ["books", "thought"], "born_date": "January 12, 1949", "born_location": "in Kyoto, Japan", "desciption": "Haruki Murakami (Japanese: 村上 春樹) is a popular contemporary Japanese writer and translator. His work"}
{"text": "When one door of happiness closes, another opens; but often we look so long at the closed door that we do not see the one which has been opened for us.", "author": "Helen Keller", "tags": ["inspirational"], "born_date": "June 27, 1880", "born_location": "in Tuscumbia, Alabama, The United States", "desciption": "Helen Keller would not be bound by conditions. Rendered deaf and blind at 19 months by scarlet fever"}
{"text": "Not all those who wander are lost.", "author": "J.R.R. Tolkien", "tags": ["bilbo", "journey", "lost", "quest", "travel", "wander"], "born_date": "January 03, 1892", "born_location": "in Bloemfontein, Mangaung, Free State, South Africa", "desciption": "John Ronald Reuel Tolkien, CBE, was an English writer, poet, WWI veteran (a First Lieutenant in the "}
{"text": "You don’t forget the face of the person who was your last hope.", "author": "Suzanne Collins", "tags": ["the-hunger-games"], "born_date": "August 11, 1962", "born_location": "in Hartford, Connecticut, The United States", "desciption": "Librarian Note: There is more than one author in the Goodreads database with this name.Since 1991, S"}
{"text": "That's the problem with drinking, I thought, as I poured myself a drink. If something bad happens you drink in an attempt to forget; if something good happens you drink in order to celebrate; and if nothing happens you drink to make something happen.", "author": "Charles Bukowski", "tags": ["alcohol"], "born_date": "August 16, 1920", "born_location": "in Andernach, Germany", "desciption": "Henry Charles Bukowski (born as Heinrich Karl Bukowski) was a German-born American poet, novelist an"}
{"text": "I am free of all prejudice. I hate everyone equally. ", "author": "W.C. Fields", "tags": ["humor", "sinister"], "born_date": "January 29, 1880", "born_location": "in Darby, Pennsylvania, The United States", "desciption": "W. C. Fields was born William Claude Dukenfield, the eldest of five children. Field's parents were a"}
{"text": "You may say I'm a dreamer, but I'm not the only one. I hope someday you'll join us. And the world will live as one.", "author": "John Lennon", "tags": ["beatles", "connection", "dreamers", "dreaming", "dreams", "hope", "inspirational", "peace"], "born_date": "October 09, 1940", "born_location": "in Liverpool, England, The United Kingdom", "desciption": "John Winston Ono Lennon, MBE, was an English singer-songwriter who rose to worldwide fame as one of "}
{"text": "The reason I talk to myself is because I’m the only one whose answers I accept.", "author": "George Carlin", "tags": ["humor", "insanity", "lies", "lying", "self-indulgence", "truth"], "born_date": "May 12, 1937", "born_location": "in New York, New York, The United States", "desciption": "George Denis Patrick Carlin was a Grammy-winning American stand-up comedian, actor, author, and phil"}
{"text": "The question isn't who is going to let me; it's who is going to stop me.", "author": "Ayn Rand", "tags": [], "born_date": "February 02, 1905", "born_location": "in St. Petersburg, Russian Federation", "desciption": "Alisa Rosenbaum was born in pre-revolutionary St. Petersburg to a prosperous Jewish family. When the"}
{"text": "What really knocks me out is a book that, when you're all done reading it, you wish the author that wrote it was a terrific friend of yours and you could call him up on the phone whenever you felt like it. That doesn't happen much, though.", "author": "J.D. Salinger", "tags": ["authors", "books", "literature", "reading", "writing"], "born_date": "January 01, 1919", "born_location": "in Manhattan, New York, The United States", "desciption": "Jerome David Salinger was an American author, best known for his 1951 novel The Catcher in the Rye, "}
{"text": "The trouble with having an open mind, of course, is that people will insist on coming along and trying to put things in it.", "author": "Terry Pratchett", "tags": ["humor", "open-mind", "thinking"], "born_date": "April 28, 1948", "born_location": "in Beaconsfield, Buckinghamshire, England, The United Kingdom", "desciption": "Sir Terry Pratchett sold his first story when he was thirteen, which earned him enough money to buy "}
{"text": "If I had a flower for every time I thought of you...I could walk through my garden forever.", "author": "Alfred Tennyson", "tags": ["friendship", "love"], "born_date": "August 06, 1809", "born_location": "in Somersby, Lincolnshire, The United Kingdom", "desciption": "Alfred Tennyson was born in Somersby, Lincolnshire, the fourth of the twelve children of George Tenn"}
{"text": "But better to get hurt by the truth than comforted with a lie.", "author": "Khaled Hosseini", "tags": ["life"], "born_date": "March 04, 1965", "born_location": "in Kabul, Afghanistan", "desciption": "Hosseini was born in Kabul, Afghanistan, in 1965. In 1970 Hosseini and his family moved to Iran wher"}
{"text": "It takes courage to grow up and become who you really are.", "author": "E.E. Cummings", "tags": ["courage"], "born_date": "October 14, 1894", "born_location": "in Cambridge, Massachusetts, The United States", "desciption": "Edward Estlin Cummings was born in Cambridge, Massachusetts, on October 14, 1894. He began writing p"}
{"text": "I'm the one that's got to die when it's time for me to die, so let me live my life the way I want to.", "author": "Jimi Hendrix", "tags": ["death", "life"], "born_date": "November 27, 1942", "born_location": "in Seattle, Washington, The United States", "desciption": "Jimi Hendrix was an American guitarist, singer and songwriter. Hendrix is considered one of the grea"}
{"text": "You have to write the book that wants to be written. And if the book will be too difficult for grown-ups, then you write it for children.", "author": "Madeleine L'Engle", "tags": ["books", "children", "difficult", "grown-ups", "write", "writers", "writing"], "born_date": "November 29, 1918", "born_location": "in New York City, New York, The United States", "desciption": "Madeleine L'Engle was an American writer best known for her Young Adult fiction, particularly the Ne"}
{"text": "To die will be an awfully big adventure.", "author": "J.M. Barrie", "tags": ["adventure", "love"], "born_date": "May 09, 1860", "born_location": "in Kirriemuir, Angus, Scotland, The United Kingdom", "desciption": "Sir James Matthew Barrie, 1st Baronet, OM (9 May 1860 – 19 June 1937) was a Scottish author and dram"}
{"text": "You never really understand a person until you consider things from his point of view... Until you climb inside of his skin and walk around in it.", "author": "Harper Lee", "tags": ["better-life-empathy"], "born_date": "April 28, 1926", "born_location": "in Monroeville, Alabama, The United States", "desciption": "Harper Lee, known as Nelle, was born in the Alabama town of Monroeville, the youngest of four childr"}
