{"username": "donnemartin", "userurl": "github.com/donnemartin", "projname": "system-design-primer", "projurl": "github.com/donnemartin/system-design-primer", "star": "200080", "about": "Learn how to design large-scale systems. Prep for the system design interview.  Includes Anki flashcards.", "topics": ["python", "design", "development", "programming", "web", "system", "design-patterns", "interview", "web-application", "webapp", "interview-practice", "interview-questions", "design-system"], "update": "Oct 15, 2022"}
{"username": "tensorflow", "userurl": "github.com/tensorflow", "projname": "tensorflow", "projurl": "github.com/tensorflow/tensorflow", "star": "168421", "about": "An Open Source Machine Learning Framework for Everyone", "topics": ["python", "machine-learning", "deep-neural-networks", "deep-learning", "neural-network", "tensorflow", "ml", "distributed"], "update": "Oct 17, 2022"}
{"username": "CyC2018", "userurl": "github.com/CyC2018", "projname": "CS-Notes", "projurl": "github.com/CyC2018/CS-Notes", "star": "157617", "about": "技术面试必备基础知识、Leetcode、计算机操作系统、计算机网络、系统设计", "topics": ["python", "java", "computer-science", "algorithm", "leetcode", "cpp", "interview", "system-design"], "update": "Oct 7, 2022"}
{"username": "TheAlgorithms", "userurl": "github.com/TheAlgorithms", "projname": "Python", "projurl": "github.com/TheAlgorithms/Python", "star": "146978", "about": "All Algorithms implemented in Python", "topics": ["python", "education", "algorithm", "practice", "interview", "sorting-algorithms", "learn", "algos", "algorithm-competitions", "sorts", "hacktoberfest", "algorithms-implemented", "community-driven", "searches"], "update": "Oct 17, 2022"}
{"username": "vinta", "userurl": "github.com/vinta", "projname": "awesome-python", "projurl": "github.com/vinta/awesome-python", "star": "144617", "about": "A curated list of awesome Python frameworks, libraries, software and resources", "topics": ["python", "awesome", "python-library", "collections", "python-framework", "python-resources"], "update": "Oct 13, 2022"}
{"username": "justjavac", "userurl": "github.com/justjavac", "projname": "free-programming-books-zh_CN", "projurl": "github.com/justjavac/free-programming-books-zh_CN", "star": "96139", "about": "免费的计算机编程类中文书籍，欢迎投稿", "topics": ["react", "javascript", "android", "kotlin", "python", "swift", "pdf", "ios", "angular", "react-native", "programming", "books", "vue", "free"], "update": "Aug 13, 2022"}
{"username": "practical-tutorials", "userurl": "github.com/practical-tutorials", "projname": "project-based-learning", "projurl": "github.com/practical-tutorials/project-based-learning", "star": "79264", "about": "Curated list of project-based tutorials", "topics": ["javascript", "python", "golang", "tutorial", "cpp", "beginner-project", "project", "webdevelopment"], "update": "Oct 6, 2022"}
{"username": "nvbn", "userurl": "github.com/nvbn", "projname": "thefuck", "projurl": "github.com/nvbn/thefuck", "star": "74092", "about": "Magnificent app which corrects your previous console command.", "topics": ["python", "shell"], "update": "Sep 30, 2022"}
{"username": "huggingface", "userurl": "github.com/huggingface", "projname": "transformers", "projurl": "github.com/huggingface/transformers", "star": "72346", "about": "Transformers: State-of-the-art Machine Learning for Pytorch, TensorFlow, and JAX.", "topics": ["python", "nlp", "machine-learning", "natural-language-processing", "deep-learning", "tensorflow", "pytorch", "transformer", "speech-recognition", "seq2seq", "flax", "pretrained-models", "language-models", "nlp-library", "language-model", "hacktoberfest", "bert", "jax", "pytorch-transformers", "model-hub"], "update": "Oct 17, 2022"}
{"username": "django", "userurl": "github.com/django", "projname": "django", "projurl": "github.com/django/django", "star": "66828", "about": "The Web framework for perfectionists with deadlines.", "topics": ["python", "django", "views", "framework", "orm", "web", "apps", "templates", "models"], "update": "Oct 17, 2022"}
{"username": "pallets", "userurl": "github.com/pallets", "projname": "flask", "projurl": "github.com/pallets/flask", "star": "60837", "about": "The Python micro framework for building web applications.", "topics": ["python", "flask", "web-framework", "wsgi", "jinja", "werkzeug", "pallets"], "update": "Oct 15, 2022"}
{"username": "521xueweihan", "userurl": "github.com/521xueweihan", "projname": "HelloGitHub", "projurl": "github.com/521xueweihan/HelloGitHub", "star": "60245", "about": "分享 GitHub 上有趣、入门级的开源项目。Share interesting, entry-level open source projects on GitHub.", "topics": ["github", "python", "awesome", "hellogithub"], "update": "Oct 9, 2022"}
{"username": "pytorch", "userurl": "github.com/pytorch", "projname": "pytorch", "projurl": "github.com/pytorch/pytorch", "star": "59625", "about": "Tensors and Dynamic neural networks in Python with strong GPU acceleration", "topics": ["python", "machine-learning", "deep-learning", "neural-network", "gpu", "numpy", "autograd", "tensor"], "update": "Oct 17, 2022"}
{"username": "keras-team", "userurl": "github.com/keras-team", "projname": "keras", "projurl": "github.com/keras-team/keras", "star": "56412", "about": "Deep Learning for humans", "topics": ["python", "data-science", "machine-learning", "deep-learning", "tensorflow", "neural-networks"], "update": "Oct 15, 2022"}
{"username": "home-assistant", "userurl": "github.com/home-assistant", "projname": "core", "projurl": "github.com/home-assistant/core", "star": "55328", "about": "Open source home automation that puts local control and privacy first.", "topics": ["python", "home-automation", "mqtt", "raspberry-pi", "iot", "internet-of-things", "asyncio", "hacktoberfest"], "update": "Oct 17, 2022"}
{"username": "ansible", "userurl": "github.com/ansible", "projname": "ansible", "projurl": "github.com/ansible/ansible", "star": "55065", "about": "Ansible is a radically simple IT automation platform that makes your applications and systems easier to deploy and maintain. Automate everything from code deployment to network configuration to cloud management, in a language that approaches plain English, using SSH, with no agents to install on remote systems.", "topics": ["python", "ansible", "hacktoberfest"], "update": "Oct 16, 2022"}
{"username": "scikit-learn", "userurl": "github.com/scikit-learn", "projname": "scikit-learn", "projurl": "github.com/scikit-learn/scikit-learn", "star": "51721", "about": "scikit-learn: machine learning in Python", "topics": ["python", "data-science", "machine-learning", "statistics", "data-analysis"], "update": "Oct 17, 2022"}
{"username": "tiangolo", "userurl": "github.com/tiangolo", "projname": "fastapi", "projurl": "github.com/tiangolo/fastapi", "star": "50572", "about": "FastAPI framework, high performance, easy to learn, fast to code, ready for production", "topics": ["python", "api", "json", "framework", "web", "rest", "json-schema", "async", "swagger", "openapi", "python3", "asyncio", "swagger-ui", "redoc", "openapi3", "python-types", "uvicorn", "starlette", "pydantic", "fastapi"], "update": "Oct 16, 2022"}
{"username": "azl397985856", "userurl": "github.com/azl397985856", "projname": "leetcode", "projurl": "github.com/azl397985856/leetcode", "star": "49594", "about": "推荐刷题网站：", "topics": ["javascript", "python", "java", "computer-science", "tree", "algorithm", "algorithms", "leetcode", "cpp", "interview", "algo", "data-structures", "leetcode-solutions", "algorithms-datastructures"], "update": "Oct 17, 2022"}
{"username": "apache", "userurl": "github.com/apache", "projname": "superset", "projurl": "github.com/apache/superset", "star": "48595", "about": "Apache Superset is a Data Visualization and Data Exploration Platform", "topics": ["react", "python", "flask", "data-science", "bi", "analytics", "superset", "apache", "data-visualization", "data-engineering", "business-intelligence", "data-viz", "data-analytics", "data-analysis", "sql-editor", "asf", "business-analytics", "apache-superset"], "update": "Oct 17, 2022"}
{"username": "locustio", "userurl": "github.com/locustio", "projname": "locust", "projurl": "github.com/locustio/locust", "star": "19931", "about": "Scalable user load testing tool written in Python", "topics": ["python", "http", "benchmarking", "load-testing", "locust", "load-generator", "performance-testing"], "update": "Oct 17, 2022"}
{"username": "httpie", "userurl": "github.com/httpie", "projname": "httpie", "projurl": "github.com/httpie/httpie", "star": "24266", "about": "HTTPie for Terminal — modern, user-friendly command-line HTTP client for the API era. JSON support, colors, sessions, downloads, plugins & more.", "topics": ["python", "api", "debugging", "cli", "http", "client", "devops", "json", "development", "terminal", "web", "rest", "curl", "rest-api", "http-client", "api-client", "developer-tools", "usability", "api-testing", "httpie"], "update": "Oct 1, 2022"}
{"username": "python-telegram-bot", "userurl": "github.com/python-telegram-bot", "projname": "python-telegram-bot", "projurl": "github.com/python-telegram-bot/python-telegram-bot", "star": "19918", "about": "We have made you a wrapper you can't refuse", "topics": ["python", "bot", "framework", "telegram", "chatbot", "hacktoberfest"], "update": "Oct 16, 2022"}
{"username": "freqtrade", "userurl": "github.com/freqtrade", "projname": "freqtrade", "projurl": "github.com/freqtrade/freqtrade", "star": "19571", "about": "Free, open source crypto trading bot", "topics": ["python", "bitcoin", "telegram-bot", "trading-bot", "cryptocurrency", "cryptocurrencies", "trade", "algorithmic-trading", "freqtrade"], "update": "Oct 17, 2022"}
{"username": "facebookresearch", "userurl": "github.com/facebookresearch", "projname": "fairseq", "projurl": "github.com/facebookresearch/fairseq", "star": "19432", "about": "Facebook AI Research Sequence-to-Sequence Toolkit written in Python.", "topics": ["python", "pytorch", "artificial-intelligence"], "update": "Oct 17, 2022"}
{"username": "vnpy", "userurl": "github.com/vnpy", "projname": "vnpy", "projurl": "github.com/vnpy/vnpy", "star": "19348", "about": "基于Python的开源量化交易平台开发框架", "topics": ["python", "finance", "trading", "fintech", "algotrading", "quant", "investment", "vnpy"], "update": "Oct 1, 2022"}
{"username": "jumpserver", "userurl": "github.com/jumpserver", "projname": "jumpserver", "projurl": "github.com/jumpserver/jumpserver", "star": "19292", "about": "JumpServer 是广受欢迎的开源堡垒机，是符合 4A 规范的专业运维安全审计系统。", "topics": ["python", "django", "terminal", "ssh-server", "coco", "luna", "bastion-host", "jumpserver", "web-terminal"], "update": "Oct 17, 2022"}
{"username": "bokeh", "userurl": "github.com/bokeh", "projname": "bokeh", "projurl": "github.com/bokeh/bokeh", "star": "16789", "about": "Interactive Data Visualization in the browser, from  Python", "topics": ["visualization", "javascript", "python", "plots", "jupyter", "visualisation", "data-visualisation", "bokeh", "plotting", "notebooks", "interactive-plots", "numfocus"], "update": "Oct 16, 2022"}
{"username": "donnemartin", "userurl": "github.com/donnemartin", "projname": "data-science-ipython-notebooks", "projurl": "github.com/donnemartin/data-science-ipython-notebooks", "star": "23944", "about": "Data science Python notebooks: Deep learning (TensorFlow, Theano, Caffe, Keras), scikit-learn, Kaggle, big data (Spark, Hadoop MapReduce, HDFS), matplotlib, pandas, NumPy, SciPy, Python essentials, AWS, and various command lines.", "topics": ["python", "aws", "data-science", "machine-learning", "caffe", "theano", "big-data", "spark", "deep-learning", "hadoop", "tensorflow", "numpy", "scikit-learn", "keras", "pandas", "kaggle", "scipy", "matplotlib", "mapreduce"], "update": "Oct 12, 2022"}
{"username": "pypa", "userurl": "github.com/pypa", "projname": "pipenv", "projurl": "github.com/pypa/pipenv", "star": "23353", "about": "Python Development Workflow for Humans.", "topics": ["python", "packaging", "virtualenv", "pip", "pipfile"], "update": "Oct 16, 2022"}
{"username": "google", "userurl": "github.com/google", "projname": "python-fire", "projurl": "github.com/google/python-fire", "star": "23208", "about": "Python Fire is a library for automatically generating command line interfaces (CLIs) from absolutely any Python object.", "topics": ["python", "cli"], "update": "Sep 29, 2022"}
{"username": "tqdm", "userurl": "github.com/tqdm", "projname": "tqdm", "projurl": "github.com/tqdm/tqdm", "star": "23115", "about": "A Fast, Extensible Progress Bar for Python and CLI", "topics": ["python", "cli", "console", "gui", "time", "terminal", "telegram", "utilities", "jupyter", "progress", "discord", "progress-bar", "parallel", "keras", "meter", "progressbar", "pandas", "progressmeter", "rate", "closember"], "update": "Oct 16, 2022"}
{"username": "MLEveryday", "userurl": "github.com/MLEveryday", "projname": "100-Days-Of-ML-Code", "projurl": "github.com/MLEveryday/100-Days-Of-ML-Code", "star": "19218", "about": "100-Days-Of-ML-Code中文版", "topics": ["python", "machine-learning", "tutorial", "deep-learning", "tensorflow", "keras", "jupyter-notebook", "supervised-learning", "unsupervised-learning", "chinese-simplified", "infographics", "100-days-of-ml-code"], "update": "Apr 6, 2022"}
{"username": "norvig", "userurl": "github.com/norvig", "projname": "pytudes", "projurl": "github.com/norvig/pytudes", "star": "19216", "about": "Python programs, usually short, of considerable difficulty, to perfect particular skills.", "topics": ["python", "practice", "programming", "python-3", "demonstrate-skills"], "update": "Sep 30, 2022"}
{"username": "PaddlePaddle", "userurl": "github.com/PaddlePaddle", "projname": "Paddle", "projurl": "github.com/PaddlePaddle/Paddle", "star": "19017", "about": "PArallel Distributed Deep LEarning: Machine Learning Framework from Industrial Practice （『飞桨』核心框架，深度学习&机器学习高性能单机、分布式训练和跨平台部署）", "topics": ["python", "machine-learning", "deep-learning", "neural-network", "scalability", "efficiency", "paddlepaddle", "distributed-training"], "update": "Oct 17, 2022"}
{"username": "google", "userurl": "github.com/google", "projname": "flatbuffers", "projurl": "github.com/google/flatbuffers", "star": "18888", "about": "FlatBuffers: Memory Efficient Serialization Library", "topics": ["javascript", "python", "c", "java", "go", "c-sharp", "rust", "c-plus-plus", "serialization", "typescript", "protobuf", "cross-platform", "flatbuffers", "zero-copy", "marshalling", "grpc", "rpc", "json-parser", "mmap", "serialization-library"], "update": "Oct 14, 2022"}
{"username": "zulip", "userurl": "github.com/zulip", "projname": "zulip", "projurl": "github.com/zulip/zulip", "star": "16550", "about": "Zulip server and web app—powerful open source team chat", "topics": ["electron", "javascript", "python", "slack", "chat", "react-native", "foss", "apache", "collaboration", "python3", "free", "zulip"], "update": "Oct 17, 2022"}
{"username": "sanic-org", "userurl": "github.com/sanic-org", "projname": "sanic", "projurl": "github.com/sanic-org/sanic", "star": "16521", "about": "Next generation Python web server/framework | Build fast. Run fast.", "topics": ["python", "framework", "web-server", "web", "sanic", "web-framework", "api-server", "asyncio", "asgi"], "update": "Oct 16, 2022"}
{"username": "AtsushiSakai", "userurl": "github.com/AtsushiSakai", "projname": "PythonRobotics", "projurl": "github.com/AtsushiSakai/PythonRobotics", "star": "16508", "about": "Python sample codes for robotics algorithms.", "topics": ["python", "algorithm", "control", "robot", "localization", "robotics", "mapping", "animation", "path-planning", "slam", "autonomous-driving", "autonomous-vehicles", "ekf", "hacktoberfest", "cvxpy", "autonomous-navigation"], "update": "Oct 13, 2022"}
{"username": "kovidgoyal", "userurl": "github.com/kovidgoyal", "projname": "kitty", "projurl": "github.com/kovidgoyal/kitty", "star": "16307", "about": "Cross-platform, fast, feature-rich, GPU based terminal", "topics": ["python", "c", "terminal", "opengl", "terminfo", "terminal-emulators", "vt100"], "update": "Oct 17, 2022"}
{"username": "fastai", "userurl": "github.com/fastai", "projname": "fastai", "projurl": "github.com/fastai/fastai", "star": "22878", "about": "The fastai deep learning library", "topics": ["python", "machine-learning", "deep-learning", "gpu", "pytorch", "colab", "notebooks", "fastai"], "update": "Oct 17, 2022"}
{"username": "ray-project", "userurl": "github.com/ray-project", "projname": "ray", "projurl": "github.com/ray-project/ray", "star": "22342", "about": "Ray is a unified framework for scaling AI and Python applications. Ray consists of a core distributed runtime and a toolkit of libraries (Ray AIR) for accelerating ML workloads.", "topics": ["python", "java", "data-science", "machine-learning", "reinforcement-learning", "deep-learning", "deployment", "tensorflow", "optimization", "parallel", "pytorch", "distributed", "model-selection", "hyperparameter-optimization", "ray", "automl", "hyperparameter-search", "serving", "rllib"], "update": "Oct 17, 2022"}
{"username": "python-poetry", "userurl": "github.com/python-poetry", "projname": "poetry", "projurl": "github.com/python-poetry/poetry", "star": "22254", "about": "Python packaging and dependency management made easy", "topics": ["python", "package-manager", "dependency-manager", "packaging", "poetry"], "update": "Oct 16, 2022"}
{"username": "itdevbooks", "userurl": "github.com/itdevbooks", "projname": "pdf", "projurl": "github.com/itdevbooks/pdf", "star": "18207", "about": "编程电子书，电子书，编程书籍，包括C，C#，Docker，Elasticsearch，Git，Hadoop，HeadFirst，Java，Javascript，jvm，Kafka，Linux，Maven，MongoDB，MyBatis，MySQL，Netty，Nginx，Python，RabbitMQ，Redis，Scala，Solr，Spark，Spring，SpringBoot，SpringCloud，TCPIP，Tomcat，Zookeeper，人工智能，大数据类，并发编程，数据库类，数据挖掘，新面试题，架构设计，算法系列，计算机类，设计模式，软件测试，重构优化，等更多分类", "topics": ["mysql", "python", "linux", "docker", "redis", "elasticsearch", "spark", "spring", "hadoop", "rabbitmq", "solr", "jvm", "netty", "springboot", "mybatis", "springcloud"], "update": "May 18, 2022"}
{"username": "cookiecutter", "userurl": "github.com/cookiecutter", "projname": "cookiecutter", "projurl": "github.com/cookiecutter/cookiecutter", "star": "18195", "about": "A cross-platform command-line utility that creates projects from cookiecutters (project templates), e.g. Python package projects, C projects.", "topics": ["python", "cookiecutter"], "update": "Oct 14, 2022"}
{"username": "facert", "userurl": "github.com/facert", "projname": "awesome-spider", "projurl": "github.com/facert/awesome-spider", "star": "18093", "about": "爬虫集合", "topics": ["python", "awesome", "spider"], "update": "May 19, 2022"}
{"username": "HelloZeroNet", "userurl": "github.com/HelloZeroNet", "projname": "ZeroNet", "projurl": "github.com/HelloZeroNet/ZeroNet", "star": "17654", "about": "ZeroNet - Decentralized websites using Bitcoin crypto and BitTorrent network", "topics": ["python", "torrent", "web", "bittorrent", "bitcoin", "decentralized", "realtime", "p2p", "tor", "anticensorship", "internet-freedom", "anonymity"], "update": "Oct 8, 2022"}
{"username": "microsoft", "userurl": "github.com/microsoft", "projname": "Data-Science-For-Beginners", "projurl": "github.com/microsoft/Data-Science-For-Beginners", "star": "16280", "about": "10 Weeks, 20 Lessons, Data Science for All!", "topics": ["python", "data-science", "pandas", "data-visualization", "data-analysis"], "update": "Oct 11, 2022"}
{"username": "fastai", "userurl": "github.com/fastai", "projname": "fastbook", "projurl": "github.com/fastai/fastbook", "star": "16273", "about": "The fastai book, published as Jupyter Notebooks", "topics": ["python", "data-science", "machine-learning", "deep-learning", "book", "notebooks", "fastai"], "update": "Sep 27, 2022"}
{"username": "matplotlib", "userurl": "github.com/matplotlib", "projname": "matplotlib", "projurl": "github.com/matplotlib/matplotlib", "star": "16266", "about": "matplotlib: plotting with Python", "topics": ["python", "gtk", "data-science", "qt", "data-visualization", "tk", "matplotlib", "plotting", "hacktoberfest", "wx"], "update": "Oct 17, 2022"}
{"username": "instillai", "userurl": "github.com/instillai", "projname": "TensorFlow-Course", "projurl": "github.com/instillai/TensorFlow-Course", "star": "16222", "about": "Simple and ready-to-use tutorials for TensorFlow", "topics": ["python", "deep-learning", "tensorflow", "deep-learning-tutorial"], "update": "Aug 13, 2021"}
{"username": "reddit-archive", "userurl": "github.com/reddit-archive", "projname": "reddit", "projurl": "github.com/reddit-archive/reddit", "star": "16195", "about": "historical code from reddit.com", "topics": ["javascript", "python", "reddit"], "update": "Oct 17, 2017"}
{"username": "getredash", "userurl": "github.com/getredash", "projname": "redash", "projurl": "github.com/getredash/redash", "star": "21911", "about": "Make Your Company Data Driven. Connect to any data source, easily visualize, dashboard and share your data.", "topics": ["visualization", "javascript", "mysql", "python", "bigquery", "bi", "spark", "dashboard", "athena", "analytics", "postgresql", "business-intelligence", "redash", "redshift", "databricks", "hacktoberfest", "spark-sql"], "update": "Oct 14, 2022"}
{"username": "keon", "userurl": "github.com/keon", "projname": "algorithms", "projurl": "github.com/keon/algorithms", "star": "21710", "about": "Minimal examples of data structures and algorithms in Python", "topics": ["python", "search", "tree", "algorithm", "data-structure", "algorithms", "graph", "competitive-programming", "sort"], "update": "Oct 4, 2022"}
{"username": "numpy", "userurl": "github.com/numpy", "projname": "numpy", "projurl": "github.com/numpy/numpy", "star": "21706", "about": "The fundamental package for scientific computing with Python.", "topics": ["python", "numpy"], "update": "Oct 17, 2022"}
{"username": "StevenBlack", "userurl": "github.com/StevenBlack", "projname": "hosts", "projurl": "github.com/StevenBlack/hosts", "star": "21670", "about": "Consolidating and extending hosts files from several well-curated sources. Optionally pick extensions for porn, social media, and other categories.", "topics": ["python", "security", "privacy", "protection", "anti-virus", "malware", "ad-blocker", "unified-hosts", "porn-filter", "social-media-filter", "hosts", "gambling-filter", "ransomware", "pornblocker", "trojans", "curated-sources"], "update": "Oct 16, 2022"}
{"username": "oracle", "userurl": "github.com/oracle", "projname": "graal", "projurl": "github.com/oracle/graal", "star": "17628", "about": "GraalVM: Run Programs Faster Anywhere", "topics": ["javascript", "ruby", "python", "c", "java", "vm", "r", "polyglot"], "update": "Oct 15, 2022"}
{"username": "plotly", "userurl": "github.com/plotly", "projname": "dash", "projurl": "github.com/plotly/dash", "star": "17482", "about": "Analytical Web Apps for Python, R, Julia, and Jupyter. No JavaScript Required.", "topics": ["react", "python", "productivity", "flask", "finance", "data-science", "bioinformatics", "r", "jupyter", "julia", "web-app", "modeling", "plotly", "data-visualization", "dash", "rstats", "gui-framework", "charting", "technical-computing", "plotly-dash"], "update": "Oct 15, 2022"}
{"username": "OpenBB-finance", "userurl": "github.com/OpenBB-finance", "projname": "OpenBBTerminal", "projurl": "github.com/OpenBB-finance/OpenBBTerminal", "star": "17307", "about": "Investment Research for Everyone, Anywhere.", "topics": ["python", "finance", "machine-learning", "crypto", "artificial-intelligence", "cryptocurrency", "economics", "stocks", "quantitative-finance", "investment", "hacktoberfest", "investment-research"], "update": "Oct 17, 2022"}
{"username": "microsoft", "userurl": "github.com/microsoft", "projname": "CNTK", "projurl": "github.com/microsoft/CNTK", "star": "17240", "about": "Microsoft Cognitive Toolkit (CNTK), an open source deep-learning toolkit", "topics": ["python", "java", "c-sharp", "c-plus-plus", "machine-learning", "deep-neural-networks", "deep-learning", "neural-network", "cntk", "distributed", "cognitive-toolkit"], "update": "Sep 30, 2022"}
{"username": "spotify", "userurl": "github.com/spotify", "projname": "luigi", "projurl": "github.com/spotify/luigi", "star": "16050", "about": "Luigi is a Python module that helps you build complex pipelines of batch jobs. It handles dependency resolution, workflow management, visualization etc. It also comes with Hadoop support built in.", "topics": ["python", "hadoop", "scheduling", "orchestration-framework", "luigi"], "update": "Sep 22, 2022"}
{"username": "JaidedAI", "userurl": "github.com/JaidedAI", "projname": "EasyOCR", "projurl": "github.com/JaidedAI/EasyOCR", "star": "16042", "about": "Ready-to-use OCR with 80+ supported languages and all popular writing scripts including Latin, Chinese, Arabic, Devanagari, Cyrillic and etc.", "topics": ["python", "machine-learning", "information-retrieval", "data-mining", "ocr", "deep-learning", "image-processing", "cnn", "pytorch", "lstm", "optical-character-recognition", "crnn", "scene-text", "scene-text-recognition", "easyocr"], "update": "Oct 13, 2022"}
{"username": "Asabeneh", "userurl": "github.com/Asabeneh", "projname": "30-Days-Of-Python", "projurl": "github.com/Asabeneh/30-Days-Of-Python", "star": "15765", "about": "30 days of Python programming challenge is a step-by-step guide to learn the Python programming language in 30 days. This challenge may take more than100 days, follow your own pace.", "topics": ["github", "python", "heroku", "flask", "mongodb", "numpy", "pandas", "python3", "matplotlib", "30-days-of-python"], "update": "Oct 14, 2022"}
{"username": "binux", "userurl": "github.com/binux", "projname": "pyspider", "projurl": "github.com/binux/pyspider", "star": "15615", "about": "A Powerful Spider(Web Crawler) System in Python.", "topics": ["python", "crawler"], "update": "Oct 12, 2022"}
{"username": "ipython", "userurl": "github.com/ipython", "projname": "ipython", "projurl": "github.com/ipython/ipython", "star": "15557", "about": "Official repository for IPython itself. Other repos in the IPython organization contain things like the website, documentation builds, etc.", "topics": ["python", "data-science", "jupyter", "notebook", "ipython", "repl", "hacktoberfest", "closember"], "update": "Oct 17, 2022"}
{"username": "RaRe-Technologies", "userurl": "github.com/RaRe-Technologies", "projname": "gensim", "projurl": "github.com/RaRe-Technologies/gensim", "star": "13611", "about": "Topic Modelling for Humans", "topics": ["python", "nlp", "data-science", "machine-learning", "natural-language-processing", "information-retrieval", "data-mining", "neural-network", "word2vec", "word-embeddings", "topic-modeling", "gensim", "fasttext", "document-similarity", "word-similarity"], "update": "Oct 17, 2022"}
{"username": "nicolargo", "userurl": "github.com/nicolargo", "projname": "glances", "projurl": "github.com/nicolargo/glances", "star": "21581", "about": "Glances an Eye on your system. A top/htop alternative for GNU/Linux, BSD, Mac OS and Windows operating systems.", "topics": ["python", "multi-platform", "terminal", "web", "monitoring", "system", "restful", "restful-api"], "update": "Oct 16, 2022"}
{"username": "streamlit", "userurl": "github.com/streamlit", "projname": "streamlit", "projurl": "github.com/streamlit/streamlit", "star": "20988", "about": "Streamlit — The fastest way to build data apps in Python", "topics": ["python", "data-science", "machine-learning", "deep-learning", "data-visualization", "developer-tools", "data-analysis", "streamlit"], "update": "Oct 17, 2022"}
{"username": "tornadoweb", "userurl": "github.com/tornadoweb", "projname": "tornado", "projurl": "github.com/tornadoweb/tornado", "star": "20800", "about": "Tornado is a Python web framework and asynchronous networking library, originally developed at FriendFeed.", "topics": ["python", "asynchronous"], "update": "Oct 15, 2022"}
{"username": "deezer", "userurl": "github.com/deezer", "projname": "spleeter", "projurl": "github.com/deezer/spleeter", "star": "20648", "about": "Deezer source separation library including pretrained models.", "topics": ["python", "deep-learning", "tensorflow", "model", "drums", "deezer", "pretrained-models", "bass", "audio-processing", "vocals"], "update": "Sep 30, 2022"}
{"username": "Lightning-AI", "userurl": "github.com/Lightning-AI", "projname": "lightning", "projurl": "github.com/Lightning-AI/lightning", "star": "20321", "about": "Build and train PyTorch models and connect them to the ML lifecycle using Lightning App templates, without handling DIY infrastructure, cost management, scaling, and other headaches.", "topics": ["python", "data-science", "machine-learning", "ai", "deep-learning", "pytorch", "artificial-intelligence"], "update": "Oct 17, 2022"}
{"username": "saleor", "userurl": "github.com/saleor", "projname": "saleor", "projurl": "github.com/saleor/saleor", "star": "17037", "about": "A modular, high performance, headless e-commerce platform built with Python, GraphQL, Django, and React.", "topics": ["python", "graphql", "ecommerce", "django", "shopping-cart", "commerce", "shop", "headless", "store", "ecommerce-platform", "e-commerce", "cart", "multichannel", "hacktoberfest", "graphql-api", "headless-ecommerce", "headless-commerce"], "update": "Oct 17, 2022"}
{"username": "GitHubDaily", "userurl": "github.com/GitHubDaily", "projname": "GitHubDaily", "projurl": "github.com/GitHubDaily/GitHubDaily", "star": "16913", "about": "坚持分享 GitHub 上高质量、有趣实用的开源技术教程、开发者工具、编程网站、技术资讯。A list cool, interesting projects of GitHub.", "topics": ["github", "javascript", "python", "java", "linux", "kubernetes", "markdown", "open-source", "development", "web", "ai", "frontend", "backend", "tutorials", "developer-tools", "algorithms-and-data-structures"], "update": "Jun 11, 2022"}
{"username": "quantopian", "userurl": "github.com/quantopian", "projname": "zipline", "projurl": "github.com/quantopian/zipline", "star": "15501", "about": "Zipline, a Pythonic Algorithmic Trading Library", "topics": ["python", "quant", "algorithmic-trading", "zipline"], "update": "Oct 7, 2022"}
{"username": "Jack-Cherish", "userurl": "github.com/Jack-Cherish", "projname": "python-spider", "projurl": "github.com/Jack-Cherish/python-spider", "star": "15354", "about": "Python3网络爬虫实战：淘宝、京东、网易云、B站、12306、抖音、笔趣阁、漫画小说下载、音乐电影下载等", "topics": ["python", "python3", "python-spider", "webspider"], "update": "Jul 6, 2022"}
{"username": "micropython", "userurl": "github.com/micropython", "projname": "micropython", "projurl": "github.com/micropython/micropython", "star": "15257", "about": "MicroPython - a lean and efficient Python implementation for microcontrollers and constrained systems", "topics": ["python", "microcontroller", "embedded", "micropython"], "update": "Oct 17, 2022"}
{"username": "cool-RR", "userurl": "github.com/cool-RR", "projname": "PySnooper", "projurl": "github.com/cool-RR/PySnooper", "star": "15252", "about": "Never use print for debugging again", "topics": ["python", "debugger", "logging", "debug", "introspection"], "update": "Jul 5, 2022"}
{"username": "d2l-ai", "userurl": "github.com/d2l-ai", "projname": "d2l-en", "projurl": "github.com/d2l-ai/d2l-en", "star": "15188", "about": "Interactive deep learning book with multi-framework code, math, and discussions. Adopted at 400 universities from 60 countries including Stanford, MIT, Harvard, and Cambridge.", "topics": ["python", "data-science", "machine-learning", "natural-language-processing", "computer-vision", "deep-learning", "mxnet", "book", "notebook", "tensorflow", "keras", "pytorch", "kaggle"], "update": "Oct 14, 2022"}
{"username": "powerline", "userurl": "github.com/powerline", "projname": "powerline", "projurl": "github.com/powerline/powerline", "star": "13540", "about": "Powerline is a statusline plugin for vim, and provides statuslines and prompts for several other applications, including zsh, bash, tmux, IPython, Awesome and Qtile.", "topics": ["python", "vim", "bash", "zsh", "tmux", "fish", "ipython", "prompt", "powerline", "statusline"], "update": "Jun 23, 2022"}
{"username": "bharathgs", "userurl": "github.com/bharathgs", "projname": "Awesome-pytorch-list", "projurl": "github.com/bharathgs/Awesome-pytorch-list", "star": "13464", "about": "A comprehensive list of pytorch related content on github,such as different models,implementations,helper libraries,tutorials etc.", "topics": ["python", "nlp", "data-science", "machine-learning", "natural-language-processing", "awesome", "facebook", "computer-vision", "deep-learning", "neural-network", "cv", "tutorials", "pytorch", "awesome-list", "utility-library", "probabilistic-programming", "papers", "nlp-library", "pytorch-tutorials", "pytorch-model"], "update": "Sep 26, 2022"}
{"username": "kovidgoyal", "userurl": "github.com/kovidgoyal", "projname": "calibre", "projurl": "github.com/kovidgoyal/calibre", "star": "13446", "about": "The official source code repository for the calibre ebook manager", "topics": ["python", "ebook", "epub", "kindle", "ebook-manager", "calibre", "ebook-reader", "ebooks", "ebook-formats", "epub-generation"], "update": "Oct 17, 2022"}
{"username": "walter201230", "userurl": "github.com/walter201230", "projname": "Python", "projurl": "github.com/walter201230/Python", "star": "13347", "about": "最良心的 Python 教程：", "topics": ["python", "python3"], "update": "Nov 21, 2021"}
{"username": "trekhleb", "userurl": "github.com/trekhleb", "projname": "homemade-machine-learning", "projurl": "github.com/trekhleb/homemade-machine-learning", "star": "20301", "about": "Python examples of popular machine learning algorithms with interactive Jupyter demos and math being explained", "topics": ["python", "machine-learning", "algorithm", "jupyter", "machine-learning-algorithms", "jupyter-notebook", "machinelearning"], "update": "Oct 4, 2022"}
{"username": "celery", "userurl": "github.com/celery", "projname": "celery", "projurl": "github.com/celery/celery", "star": "20278", "about": "Distributed Task Queue (development branch)", "topics": ["python", "redis", "amqp", "python-library", "sqs", "python3", "task-runner", "sqs-queue", "task-manager", "task-scheduler", "redis-queue", "queued-jobs", "queue-workers", "queue-tasks"], "update": "Oct 17, 2022"}
{"username": "apache", "userurl": "github.com/apache", "projname": "flink", "projurl": "github.com/apache/flink", "star": "19948", "about": "Apache Flink", "topics": ["python", "java", "scala", "sql", "big-data", "flink"], "update": "Oct 17, 2022"}
{"username": "virgili0", "userurl": "github.com/virgili0", "projname": "Virgilio", "projurl": "github.com/virgili0/Virgilio", "star": "13344", "about": "Your new Mentor for Data Science E-Learning.", "topics": ["python", "nlp", "learning", "data-science", "machine-learning", "statistics", "computer-vision", "study", "tensorflow", "guide", "scikit-learn", "learning-python", "path", "datascience", "business-intelligence", "guidelines", "machine-vision", "hacktoberfest", "virgilio", "studypath"], "update": "Jul 25, 2022"}
{"username": "trekhleb", "userurl": "github.com/trekhleb", "projname": "learn-python", "projurl": "github.com/trekhleb/learn-python", "star": "13317", "about": "Playground and cheatsheet for learning Python. Collection of Python scripts that are split by topics and contain code examples with explanations.", "topics": ["python", "programming-language", "learning", "learning-python", "python3", "learning-by-doing"], "update": "Oct 14, 2022"}
{"username": "wagtail", "userurl": "github.com/wagtail", "projname": "wagtail", "projurl": "github.com/wagtail/wagtail", "star": "13281", "about": "A Django content management system focused on flexibility and user experience", "topics": ["python", "cms", "django", "wagtail", "hacktoberfest"], "update": "Oct 17, 2022"}
{"username": "antlr", "userurl": "github.com/antlr", "projname": "antlr4", "projurl": "github.com/antlr/antlr4", "star": "13156", "about": "ANTLR (ANother Tool for Language Recognition) is a powerful parser generator for reading, processing, executing, or translating structured text or binary files.", "topics": ["javascript", "python", "java", "dart", "swift", "golang", "php", "parse", "csharp", "parsing", "cpp", "parser-generator", "grammar", "antlr", "antlr4", "language-recognition"], "update": "Oct 17, 2022"}
{"username": "psf", "userurl": "github.com/psf", "projname": "requests", "projurl": "github.com/psf/requests", "star": "48381", "about": "A simple, yet elegant, HTTP library.", "topics": ["python", "http", "client", "cookies", "requests", "humans", "forhumans", "python-requests"], "update": "Oct 15, 2022"}
{"username": "Delgan", "userurl": "github.com/Delgan", "projname": "loguru", "projurl": "github.com/Delgan/loguru", "star": "13131", "about": "Python logging made (stupidly) simple", "topics": ["python", "log", "logger", "logging"], "update": "Oct 10, 2022"}
{"username": "pallets", "userurl": "github.com/pallets", "projname": "click", "projurl": "github.com/pallets/click", "star": "13077", "about": "Python composable command line interface toolkit", "topics": ["python", "cli", "click", "pallets"], "update": "Oct 13, 2022"}
{"username": "CoatiSoftware", "userurl": "github.com/CoatiSoftware", "projname": "Sourcetrail", "projurl": "github.com/CoatiSoftware/Sourcetrail", "star": "12955", "about": "Sourcetrail - free and open-source interactive source explorer", "topics": ["python", "c", "java", "cpp"], "update": "Dec 13, 2021"}
{"username": "aio-libs", "userurl": "github.com/aio-libs", "projname": "aiohttp", "projurl": "github.com/aio-libs/aiohttp", "star": "12923", "about": "Asynchronous HTTP client/server framework for asyncio and Python", "topics": ["python", "http", "async", "http-client", "aiohttp", "http-server", "asyncio", "hacktoberfest"], "update": "Oct 16, 2022"}
{"username": "google", "userurl": "github.com/google", "projname": "yapf", "projurl": "github.com/google/yapf", "star": "12857", "about": "A formatter for Python files", "topics": ["python", "formatter", "google"], "update": "Oct 3, 2022"}
{"username": "pyecharts", "userurl": "github.com/pyecharts", "projname": "pyecharts", "projurl": "github.com/pyecharts/pyecharts", "star": "12826", "about": "Python Echarts Plotting Library", "topics": ["python", "echarts"], "update": "Oct 14, 2022"}
{"username": "3b1b", "userurl": "github.com/3b1b", "projname": "manim", "projurl": "github.com/3b1b/manim", "star": "47489", "about": "Animation engine for explanatory math videos", "topics": ["python", "animation", "explanatory-math-videos", "3b1b-videos"], "update": "Oct 11, 2022"}
{"username": "ageitgey", "userurl": "github.com/ageitgey", "projname": "face_recognition", "projurl": "github.com/ageitgey/face_recognition", "star": "46098", "about": "The world's simplest facial recognition api for Python and the command line", "topics": ["python", "machine-learning", "face-recognition", "face-detection"], "update": "Sep 21, 2022"}
{"username": "scrapy", "userurl": "github.com/scrapy", "projname": "scrapy", "projurl": "github.com/scrapy/scrapy", "star": "44874", "about": "Scrapy, a fast high-level web crawling & scraping framework for Python.", "topics": ["python", "crawler", "framework", "scraping", "crawling", "hacktoberfest"], "update": "Oct 15, 2022"}
{"username": "localstack", "userurl": "github.com/localstack", "projname": "localstack", "projurl": "github.com/localstack/localstack", "star": "44066", "about": "A fully functional local AWS cloud stack. Develop and test your cloud & Serverless apps offline!", "topics": ["python", "testing", "aws", "continuous-integration", "developer-tools", "hacktoberfest", "localstack"], "update": "Oct 17, 2022"}
{"username": "saltstack", "userurl": "github.com/saltstack", "projname": "salt", "projurl": "github.com/saltstack/salt", "star": "12795", "about": "Software to automate the management and configuration of any infrastructure or application at scale. Get access to the Salt software package repository here:", "topics": ["python", "iot", "cloud", "event-stream", "zeromq", "cloud-providers", "event-management", "configuration-management", "edge", "remote-execution", "infrastructure-management", "cloud-management", "cloud-provisioning", "infrastructure-as-code", "infrastructure-automation", "infrastructure-as-a-code", "infrasructure"], "update": "Oct 17, 2022"}
{"username": "dragen1860", "userurl": "github.com/dragen1860", "projname": "Deep-Learning-with-TensorFlow-book", "projurl": "github.com/dragen1860/Deep-Learning-with-TensorFlow-book", "star": "12773", "about": "深度学习入门开源书，基于TensorFlow 2.0案例实战。Open source Deep Learning book, based on TensorFlow 2.0 framework.", "topics": ["python", "opensource", "book", "tensorflow", "pytorch", "machinelearning", "deeplearning", "tensorflow2"], "update": "Aug 30, 2021"}
{"username": "psf", "userurl": "github.com/psf", "projname": "requests-html", "projurl": "github.com/psf/requests-html", "star": "12768", "about": "Pythonic HTML Parsing for Humans™", "topics": ["python", "html", "http", "scraping", "requests", "kennethreitz", "beautifulsoup", "lxml", "css-selectors", "pyquery"], "update": "Jul 30, 2022"}
{"username": "deeplearning4j", "userurl": "github.com/deeplearning4j", "projname": "deeplearning4j", "projurl": "github.com/deeplearning4j/deeplearning4j", "star": "12648", "about": "Suite of tools for deploying and training deep learning models using the JVM. Highlights include model import for keras, tensorflow, and onnx/pytorch, a modular and tiny c++ library for running math code and a java based math library on top of the core c++ library. Also includes samediff: a pytorch/tensorflow like library for running deep learning using automatic differentiation.", "topics": ["python", "java", "clojure", "scala", "spark", "hadoop", "gpu", "intellij", "linear-algebra", "artificial-intelligence", "deeplearning", "neural-nets", "dl4j", "matrix-library", "deeplearning4j"], "update": "Oct 17, 2022"}
{"username": "microsoft", "userurl": "github.com/microsoft", "projname": "ML-For-Beginners", "projurl": "github.com/microsoft/ML-For-Beginners", "star": "42522", "about": "12 weeks, 26 lessons, 52 quizzes, classic Machine Learning for all", "topics": ["python", "education", "data-science", "machine-learning", "r", "scikit-learn", "machine-learning-algorithms", "ml", "machinelearning", "machinelearning-python", "scikit-learn-python"], "update": "Oct 11, 2022"}
{"username": "aymericdamien", "userurl": "github.com/aymericdamien", "projname": "TensorFlow-Examples", "projurl": "github.com/aymericdamien/TensorFlow-Examples", "star": "42297", "about": "TensorFlow Tutorial and Examples for Beginners (support TF v1 & v2)", "topics": ["python", "machine-learning", "tutorial", "deep-learning", "examples", "tensorflow"], "update": "Aug 30, 2022"}
{"username": "Textualize", "userurl": "github.com/Textualize", "projname": "rich", "projurl": "github.com/Textualize/rich", "star": "40231", "about": "Rich is a Python library for rich text and beautiful formatting in the terminal.", "topics": ["python", "emoji", "syntax-highlighting", "markdown", "terminal", "progress-bar", "python-library", "python3", "traceback", "ansi-colors", "rich", "tables", "terminal-color", "progress-bar-python", "tracebacks-rich"], "update": "Oct 17, 2022"}
{"username": "ryanoasis", "userurl": "github.com/ryanoasis", "projname": "nerd-fonts", "projurl": "github.com/ryanoasis/nerd-fonts", "star": "38860", "about": "Iconic font aggregator, collection, & patcher. 3,600+ icons, 50+ patched fonts: Hack, Source Code Pro, more. Glyph collections: Font Awesome, Material Design Icons, Octicons, & more", "topics": ["python", "octicons", "shell", "font", "fonts", "patcher", "font-awesome", "icon-font", "powerline", "statusline", "iconic-fonts", "patched-fonts"], "update": "Oct 14, 2022"}
{"username": "MobSF", "userurl": "github.com/MobSF", "projname": "Mobile-Security-Framework-MobSF", "projurl": "github.com/MobSF/Mobile-Security-Framework-MobSF", "star": "12632", "about": "Mobile Security Framework (MobSF) is an automated, all-in-one mobile application (Android/iOS/Windows) pen-testing, malware analysis and security assessment framework capable of performing static and dynamic analysis.", "topics": ["python", "rest", "static-analysis", "apk", "owasp", "dynamic-analysis", "web-security", "malware-analysis", "mobsf", "android-security", "mobile-security", "windows-mobile-security", "ios-security", "mobile-security-framework", "api-testing", "cwe", "devsecops", "runtime-security", "mstg", "masvs"], "update": "Oct 16, 2022"}
{"username": "Avik-Jain", "userurl": "github.com/Avik-Jain", "projname": "100-Days-Of-ML-Code", "projurl": "github.com/Avik-Jain/100-Days-Of-ML-Code", "star": "38628", "about": "100 Days of ML Coding", "topics": ["python", "machine-learning", "tutorial", "deep-learning", "svm", "linear-regression", "scikit-learn", "linear-algebra", "machine-learning-algorithms", "naive-bayes-classifier", "logistic-regression", "implementation", "support-vector-machines", "100-days-of-code-log", "100daysofcode", "infographics", "siraj-raval", "siraj-raval-challenge"], "update": "Jul 25, 2022"}
{"username": "CorentinJ", "userurl": "github.com/CorentinJ", "projname": "Real-Time-Voice-Cloning", "projurl": "github.com/CorentinJ/Real-Time-Voice-Cloning", "star": "37120", "about": "Clone a voice in 5 seconds to generate arbitrary speech in real-time", "topics": ["python", "deep-learning", "tensorflow", "pytorch", "tts", "voice-cloning"], "update": "Sep 9, 2022"}
{"username": "sherlock-project", "userurl": "github.com/sherlock-project", "projname": "sherlock", "projurl": "github.com/sherlock-project/sherlock", "star": "36451", "about": "Hunt down social media accounts by username across social networks", "topics": ["python", "windows", "macos", "linux", "cli", "osint", "tools", "sherlock", "python3", "hacktoberfest", "information-gathering", "reconnaissance", "redteam", "hacktoberfest2022"], "update": "Oct 16, 2022"}
{"username": "jakevdp", "userurl": "github.com/jakevdp", "projname": "PythonDataScienceHandbook", "projurl": "github.com/jakevdp/PythonDataScienceHandbook", "star": "36240", "about": "Python Data Science Handbook: full text in Jupyter Notebooks", "topics": ["python", "numpy", "scikit-learn", "jupyter-notebook", "pandas", "matplotlib"], "update": "Oct 4, 2022"}
{"username": "d2l-ai", "userurl": "github.com/d2l-ai", "projname": "d2l-zh", "projurl": "github.com/d2l-ai/d2l-zh", "star": "35670", "about": "《动手学深度学习》：面向中文读者、能运行、可讨论。中英文版被60个国家的400所大学用于教学。", "topics": ["python", "machine-learning", "natural-language-processing", "computer-vision", "deep-learning", "book", "notebook", "chinese"], "update": "Oct 16, 2022"}
{"username": "pandas-dev", "userurl": "github.com/pandas-dev", "projname": "pandas", "projurl": "github.com/pandas-dev/pandas", "star": "35586", "about": "Flexible and powerful data analysis / manipulation library for Python, providing labeled data structures similar to R data.frame objects, statistical functions, and much more", "topics": ["python", "data-science", "flexible", "pandas", "alignment", "data-analysis"], "update": "Oct 17, 2022"}
{"username": "faif", "userurl": "github.com/faif", "projname": "python-patterns", "projurl": "github.com/faif/python-patterns", "star": "35254", "about": "A collection of design patterns/idioms in Python", "topics": ["python", "idioms", "design-patterns"], "update": "Aug 21, 2022"}
{"username": "apache", "userurl": "github.com/apache", "projname": "spark", "projurl": "github.com/apache/spark", "star": "34119", "about": "Apache Spark - A unified analytics engine for large-scale data processing", "topics": ["python", "java", "r", "scala", "sql", "big-data", "spark", "jdbc"], "update": "Oct 17, 2022"}
{"username": "apachecn", "userurl": "github.com/apachecn", "projname": "ailearning", "projurl": "github.com/apachecn/ailearning", "star": "34083", "about": "AiLearning：数据分析+机器学习实战+线性代数+PyTorch+NLTK+TF2", "topics": ["python", "nlp", "svm", "scikit-learn", "sklearn", "regression", "logistic", "dnn", "lstm", "pca", "rnn", "deeplearning", "kmeans", "adaboost", "apriori", "fp-growth", "svd", "naivebayes", "mahchine-leaning", "recommendedsystem"], "update": "Jul 7, 2022"}
{"username": "yt-dlp", "userurl": "github.com/yt-dlp", "projname": "yt-dlp", "projurl": "github.com/yt-dlp/yt-dlp", "star": "33681", "about": "A youtube-dl fork with additional features and fixes", "topics": ["python", "youtube-dl", "video-downloader", "youtube-downloader", "hacktoberfest", "sponsorblock", "youtube-dlc", "sponskrub", "yt-dlp"], "update": "Oct 17, 2022"}
{"username": "serhii-londar", "userurl": "github.com/serhii-londar", "projname": "open-source-mac-os-apps", "projurl": "github.com/serhii-londar/open-source-mac-os-apps", "star": "32575", "about": "Awesome list of open source applications for macOS.", "topics": ["javascript", "ruby", "python", "c", "macos", "swift", "open-source", "mac", "c-plus-plus", "awesome", "opensource", "objective-c", "apps", "applications", "macosx", "awesome-list", "hacktoberfest", "macos-application"], "update": "Oct 14, 2022"}
{"username": "youngyangyang04", "userurl": "github.com/youngyangyang04", "projname": "leetcode-master", "projurl": "github.com/youngyangyang04/leetcode-master", "star": "32453", "about": "《代码随想录》LeetCode 刷题攻略：200道经典题目刷题顺序，共60w字的详细图解，视频难点剖析，50余张思维导图，支持C++，Java，Python，Go，JavaScript等多语言版本，从此算法学习不再迷茫！", "topics": ["javascript", "python", "java", "go", "algorithm", "leetcode", "cpp", "interview", "programmer", "offer"], "update": "Oct 17, 2022"}
{"username": "getsentry", "userurl": "github.com/getsentry", "projname": "sentry", "projurl": "github.com/getsentry/sentry", "star": "32286", "about": "Sentry is cross-platform application monitoring, with a focus on error reporting.", "topics": ["python", "devops", "django", "monitor", "monitoring", "crash-reporting", "error-monitoring", "sentry", "crash-reports", "csp-report", "apm", "hacktoberfest", "error-logging"], "update": "Oct 17, 2022"}
{"username": "satwikkansal", "userurl": "github.com/satwikkansal", "projname": "wtfpython", "projurl": "github.com/satwikkansal/wtfpython", "star": "31799", "about": "What the f*ck Python?", "topics": ["python", "snippets", "documentation", "wtf", "gotchas", "interview-questions", "python-interview-questions", "pitfalls", "wats"], "update": "Sep 18, 2022"}
{"username": "bregman-arie", "userurl": "github.com/bregman-arie", "projname": "devops-exercises", "projurl": "github.com/bregman-arie/devops-exercises", "star": "31345", "about": "Linux, Jenkins, AWS, SRE, Prometheus, Docker, Python, Ansible, Git, Kubernetes, Terraform, OpenStack, SQL, NoSQL, Azure, GCP, DNS, Elastic, Network, Virtualization. DevOps Interview Questions", "topics": ["python", "git", "linux", "docker", "kubernetes", "aws", "ansible", "devops", "sql", "azure", "containers", "terraform", "openstack", "interview", "prometheus", "coding", "sre", "interview-questions", "production-engineer"], "update": "Oct 17, 2022"}
{"username": "GokuMohandas", "userurl": "github.com/GokuMohandas", "projname": "Made-With-ML", "projurl": "github.com/GokuMohandas/Made-With-ML", "star": "31155", "about": "Learn how to responsibly deliver value with machine learning.", "topics": ["python", "data-science", "machine-learning", "natural-language-processing", "deep-learning", "pytorch", "data-engineering", "mlops"], "update": "Oct 5, 2022"}
{"username": "gto76", "userurl": "github.com/gto76", "projname": "python-cheatsheet", "projurl": "github.com/gto76/python-cheatsheet", "star": "30328", "about": "Comprehensive Python Cheatsheet", "topics": ["python", "reference", "cheatsheet", "python-cheatsheet"], "update": "Oct 12, 2022"}
{"username": "psf", "userurl": "github.com/psf", "projname": "black", "projurl": "github.com/psf/black", "star": "29812", "about": "The uncompromising Python code formatter", "topics": ["python", "formatter", "code", "yapf", "gofmt", "autopep8", "hacktoberfest", "codeformatter", "pre-commit-hook"], "update": "Oct 17, 2022"}
{"username": "certbot", "userurl": "github.com/certbot", "projname": "certbot", "projurl": "github.com/certbot/certbot", "star": "29347", "about": "Certbot is EFF's tool to obtain certs from Let's Encrypt and (optionally) auto-enable HTTPS on your server.  It can also act as a client for any other CA that uses the ACME protocol.", "topics": ["python", "letsencrypt", "acme-client", "certificate", "acme", "certbot"], "update": "Oct 15, 2022"}
{"username": "pyenv", "userurl": "github.com/pyenv", "projname": "pyenv", "projurl": "github.com/pyenv/pyenv", "star": "29067", "about": "Simple Python version management", "topics": ["python", "shell"], "update": "Oct 17, 2022"}
{"username": "mitmproxy", "userurl": "github.com/mitmproxy", "projname": "mitmproxy", "projurl": "github.com/mitmproxy/mitmproxy", "star": "28966", "about": "An interactive TLS-capable intercepting HTTP proxy for penetration testers and software developers.", "topics": ["python", "tls", "debugging", "ssl", "http", "security", "proxy", "websocket", "http2", "man-in-the-middle", "hacktoberfest"], "update": "Oct 16, 2022"}
{"username": "apache", "userurl": "github.com/apache", "projname": "airflow", "projurl": "github.com/apache/airflow", "star": "27857", "about": "Apache Airflow - A platform to programmatically author, schedule, and monitor workflows", "topics": ["python", "workflow", "airflow", "scheduler", "apache", "hacktoberfest", "apache-airflow"], "update": "Oct 17, 2022"}
{"username": "odoo", "userurl": "github.com/odoo", "projname": "odoo", "projurl": "github.com/odoo/odoo", "star": "26592", "about": "Odoo. Open Source Apps To Grow Your Business.", "topics": ["python", "business", "erp", "apps", "management", "odoo", "odoo-apps"], "update": "Oct 17, 2022"}
{"username": "donnemartin", "userurl": "github.com/donnemartin", "projname": "interactive-coding-challenges", "projurl": "github.com/donnemartin/interactive-coding-challenges", "star": "26347", "about": "120+ interactive Python coding interview challenges (algorithms and data structures).  Includes Anki flashcards.", "topics": ["python", "development", "algorithm", "programming", "data-structure", "interview", "competitive-programming", "coding", "interview-practice", "interview-questions"], "update": "Oct 2, 2022"}
{"username": "realpython", "userurl": "github.com/realpython", "projname": "python-guide", "projurl": "github.com/realpython/python-guide", "star": "25455", "about": "Python best practices guidebook, written for humans.", "topics": ["python", "book", "guide", "kennethreitz"], "update": "Sep 1, 2022"}
{"username": "jobbole", "userurl": "github.com/jobbole", "projname": "awesome-python-cn", "projurl": "github.com/jobbole/awesome-python-cn", "star": "25070", "about": "Python资源大全中文版，包括：Web框架、网络爬虫、模板引擎、数据库、数据可视化、图片处理等，由「开源前哨」和「Python开发者」微信公号团队维护更新。", "topics": ["python"], "update": "Aug 29, 2022"}
{"username": "sqlmapproject", "userurl": "github.com/sqlmapproject", "projname": "sqlmap", "projurl": "github.com/sqlmapproject/sqlmap", "star": "24917", "about": "Automatic SQL injection and database takeover tool", "topics": ["python", "database", "detection", "sql-injection", "pentesting", "exploitation", "sqlmap", "takeover", "vulnerability-scanner"], "update": "Oct 15, 2022"}
{"username": "ageron", "userurl": "github.com/ageron", "projname": "handson-ml", "projurl": "github.com/ageron/handson-ml", "star": "24904", "about": "DEPRECATED – See", "topics": ["python", "machine-learning", "deep-learning", "neural-network", "tensorflow", "scikit-learn", "jupyter-notebook", "ml", "deprecated", "distributed"], "update": "Sep 30, 2022"}
{"username": "SeleniumHQ", "userurl": "github.com/SeleniumHQ", "projname": "selenium", "projurl": "github.com/SeleniumHQ/selenium", "star": "24890", "about": "A browser automation framework and ecosystem.", "topics": ["javascript", "ruby", "python", "java", "webdriver", "dotnet", "selenium"], "update": "Oct 17, 2022"}
{"username": "explosion", "userurl": "github.com/explosion", "projname": "spaCy", "projurl": "github.com/explosion/spaCy", "star": "24388", "about": "Industrial-strength Natural Language Processing (NLP) in Python", "topics": ["python", "nlp", "data-science", "machine-learning", "natural-language-processing", "ai", "deep-learning", "neural-network", "text-classification", "cython", "artificial-intelligence", "spacy", "named-entity-recognition", "neural-networks", "nlp-library", "tokenization", "entity-linking"], "update": "Oct 17, 2022"}
{"username": "encode", "userurl": "github.com/encode", "projname": "django-rest-framework", "projurl": "github.com/encode/django-rest-framework", "star": "24284", "about": "Web APIs for Django.", "topics": ["python", "api", "django", "rest"], "update": "Oct 16, 2022"}
{"username": "gunthercox", "userurl": "github.com/gunthercox", "projname": "ChatterBot", "projurl": "github.com/gunthercox/ChatterBot", "star": "12578", "about": "ChatterBot is a machine learning, conversational dialog engine for creating chat bots", "topics": ["python", "bot", "language", "machine-learning", "chatbot", "chatterbot", "conversation"], "update": "Sep 5, 2022"}
{"username": "Yixiaohan", "userurl": "github.com/Yixiaohan", "projname": "show-me-the-code", "projurl": "github.com/Yixiaohan/show-me-the-code", "star": "12504", "about": "Python 练习册，每天一个小程序", "topics": ["python", "tutorial", "python-web"], "update": "Nov 11, 2019"}
{"username": "sivel", "userurl": "github.com/sivel", "projname": "speedtest-cli", "projurl": "github.com/sivel/speedtest-cli", "star": "12278", "about": "Command line interface for testing internet bandwidth using speedtest.net", "topics": ["python", "python-library", "python-script", "speedtest"], "update": "Oct 10, 2022"}
{"username": "plotly", "userurl": "github.com/plotly", "projname": "plotly.py", "projurl": "github.com/plotly/plotly.py", "star": "12268", "about": "The interactive graphing library for Python (includes Plotly Express)", "topics": ["visualization", "d3", "python", "webgl", "dashboard", "interactive", "sparkles", "plotly", "declarative", "jupyter-notebook", "regl", "plotlyjs", "graph-library", "plotly-dash"], "update": "Oct 14, 2022"}
{"username": "RunaCapital", "userurl": "github.com/RunaCapital", "projname": "awesome-oss-alternatives", "projurl": "github.com/RunaCapital/awesome-oss-alternatives", "star": "12263", "about": "Awesome list of open-source startup alternatives to well-known SaaS products", "topics": ["python", "open-source", "list", "awesome", "unicorns", "resources", "saas", "awesome-list", "startups", "alternatives"], "update": "Oct 14, 2022"}
{"username": "codelucas", "userurl": "github.com/codelucas", "projname": "newspaper", "projurl": "github.com/codelucas/newspaper", "star": "12205", "about": "News, full-text, and article metadata extraction in Python 3. Advanced docs:", "topics": ["python", "crawler", "scraper", "news", "crawling", "news-aggregator"], "update": "Oct 4, 2022"}
{"username": "microsoft", "userurl": "github.com/microsoft", "projname": "nni", "projurl": "github.com/microsoft/nni", "star": "12087", "about": "An open source AutoML toolkit for automate machine learning lifecycle, including feature engineering, neural architecture search, model compression and hyper-parameter tuning.", "topics": ["python", "data-science", "machine-learning", "deep-learning", "neural-network", "tensorflow", "machine-learning-algorithms", "pytorch", "distributed", "hyperparameter-optimization", "feature-engineering", "nas", "bayesian-optimization", "hyperparameter-tuning", "automl", "automated-machine-learning", "model-compression", "neural-architecture-search", "deep-neural-network", "mlops"], "update": "Oct 17, 2022"}
{"username": "frappe", "userurl": "github.com/frappe", "projname": "erpnext", "projurl": "github.com/frappe/erpnext", "star": "12058", "about": "Free and Open Source Enterprise Resource Planning (ERP)", "topics": ["support", "python", "distribution", "integrations", "localization", "erp", "profit", "accounting", "crm", "healthcare", "project-management", "manufacturing", "frappe", "erpnext", "procurement", "retail", "hacktoberfest", "point-of-sale", "hrms", "asset-management"], "update": "Oct 17, 2022"}
{"username": "searx", "userurl": "github.com/searx", "projname": "searx", "projurl": "github.com/searx/searx", "star": "12032", "about": "Privacy-respecting metasearch engine", "topics": ["python", "search", "search-engine", "metasearch", "metasearch-engine"], "update": "Oct 14, 2022"}
{"username": "Miserlou", "userurl": "github.com/Miserlou", "projname": "Zappa", "projurl": "github.com/Miserlou/Zappa", "star": "11879", "about": "Serverless Python", "topics": ["python", "flask", "lambda", "django", "aws-lambda", "serverless", "api-gateway", "serverless-framework", "pyramid", "zappa", "bottle"], "update": "Jul 20, 2022"}
{"username": "waditu", "userurl": "github.com/waditu", "projname": "tushare", "projurl": "github.com/waditu/tushare", "star": "11787", "about": "TuShare is a utility for crawling historical data of China stocks", "topics": ["python", "finance", "pandas", "fintech", "stock-market", "stock-data", "tushare", "realtime-quotes-data"], "update": "Mar 28, 2022"}
{"username": "ml-tooling", "userurl": "github.com/ml-tooling", "projname": "best-of-ml-python", "projurl": "github.com/ml-tooling/best-of-ml-python", "star": "11762", "about": "A ranked list of awesome machine learning Python libraries. Updated weekly.", "topics": ["python", "nlp", "data-science", "machine-learning", "awesome", "deep-learning", "tensorflow", "scikit-learn", "python-library", "keras", "ml", "data-visualization", "pytorch", "transformer", "data-analysis", "automl", "jax", "data-visualizations", "best-of"], "update": "Oct 14, 2022"}
{"username": "rasbt", "userurl": "github.com/rasbt", "projname": "python-machine-learning-book", "projurl": "github.com/rasbt/python-machine-learning-book", "star": "11702", "about": "The \"Python Machine Learning (1st edition)\"  book code repository and info resource", "topics": ["python", "data-science", "machine-learning", "data-mining", "neural-network", "scikit-learn", "machine-learning-algorithms", "logistic-regression"], "update": "Aug 29, 2022"}
{"username": "pybind", "userurl": "github.com/pybind", "projname": "pybind11", "projurl": "github.com/pybind/pybind11", "star": "11699", "about": "Seamless operability between C++11 and Python", "topics": ["python", "bindings"], "update": "Oct 17, 2022"}
{"username": "networkx", "userurl": "github.com/networkx", "projname": "networkx", "projurl": "github.com/networkx/networkx", "star": "11680", "about": "Network Analysis in Python", "topics": ["python", "graph-algorithms", "graph-theory", "complex-networks", "graph-visualization", "graph-generation", "graph-analysis"], "update": "Oct 17, 2022"}
{"username": "Python-World", "userurl": "github.com/Python-World", "projname": "python-mini-projects", "projurl": "github.com/Python-World/python-mini-projects", "star": "11672", "about": "A collection of simple python mini projects to enhance your python skills", "topics": ["python", "opensource", "tools", "projects", "learn-to-code", "stuff", "automate", "miniprojects"], "update": "Jul 17, 2022"}
{"username": "ManimCommunity", "userurl": "github.com/ManimCommunity", "projname": "manim", "projurl": "github.com/ManimCommunity/manim", "star": "11616", "about": "A community-maintained Python framework for creating mathematical animations.", "topics": ["python", "math", "animations", "hacktoberfest", "manim"], "update": "Oct 16, 2022"}
{"username": "Rapptz", "userurl": "github.com/Rapptz", "projname": "discord.py", "projurl": "github.com/Rapptz/discord.py", "star": "11616", "about": "An API wrapper for Discord written in Python.", "topics": ["python", "bot", "discord", "discord-bot", "discord-api", "discord-py", "python-3"], "update": "Oct 14, 2022"}
{"username": "meolu", "userurl": "github.com/meolu", "projname": "walle-web", "projurl": "github.com/meolu/walle-web", "star": "11533", "about": "walle - 瓦力 Devops开源项目代码部署平台", "topics": ["python", "git", "devops", "deployer", "cd", "devops-tools", "walle-web"], "update": "Jan 6, 2022"}
{"username": "shengqiangzhang", "userurl": "github.com/shengqiangzhang", "projname": "examples-of-web-crawlers", "projurl": "github.com/shengqiangzhang/examples-of-web-crawlers", "star": "11478", "about": "一些非常有趣的python爬虫例子,对新手比较友好,主要爬取淘宝、天猫、微信、微信读书、豆瓣、QQ等网站。(Some interesting examples of python crawlers that are friendly to beginners. )", "topics": ["python", "crawler", "spider", "example", "selenium", "multithreading", "stock", "wechat", "taobao", "pyquery", "tmall", "fund", "agent-pool", "wechat-report", "wereader"], "update": "Apr 27, 2022"}
{"username": "kivy", "userurl": "github.com/kivy", "projname": "kivy", "projurl": "github.com/kivy/kivy", "star": "15119", "about": "Open source UI framework written in Python, running on Windows, Linux, macOS, Android and iOS", "topics": ["android", "python", "windows", "macos", "linux", "ios", "app", "ui", "kivy"], "update": "Oct 16, 2022"}
{"username": "mkdocs", "userurl": "github.com/mkdocs", "projname": "mkdocs", "projurl": "github.com/mkdocs/mkdocs", "star": "15112", "about": "Project documentation with Markdown.", "topics": ["python", "markdown", "static-site-generator", "documentation", "mkdocs"], "update": "Oct 16, 2022"}
{"username": "Tencent", "userurl": "github.com/Tencent", "projname": "MMKV", "projurl": "github.com/Tencent/MMKV", "star": "15088", "about": "An efficient, small mobile key-value storage framework developed by WeChat. Works on Android, iOS, macOS, Windows, and POSIX.", "topics": ["android", "kotlin", "python", "windows", "macos", "swift", "golang", "ios", "key-value", "wechat", "flutter"], "update": "Sep 29, 2022"}
{"username": "facebook", "userurl": "github.com/facebook", "projname": "prophet", "projurl": "github.com/facebook/prophet", "star": "15015", "about": "Tool for producing high quality forecasts for time series data that has multiple seasonality with linear or non-linear growth.", "topics": ["python", "r", "forecasting"], "update": "Sep 21, 2022"}
{"username": "joke2k", "userurl": "github.com/joke2k", "projname": "faker", "projurl": "github.com/joke2k/faker", "star": "14856", "about": "Faker is a Python package that generates fake data for you.", "topics": ["python", "testing", "fake", "dataset", "test-data", "fake-data", "test-data-generator"], "update": "Oct 15, 2022"}
{"username": "InstaPy", "userurl": "github.com/InstaPy", "projname": "InstaPy", "projurl": "github.com/InstaPy/InstaPy", "star": "14698", "about": "Instagram Bot - Tool for automated Instagram interactions", "topics": ["python", "bot", "instagram", "automation", "script", "selenium", "clarifai"], "update": "Aug 25, 2022"}
{"username": "pyscript", "userurl": "github.com/pyscript", "projname": "pyscript", "projurl": "github.com/pyscript/pyscript", "star": "14698", "about": "Home Page:", "topics": ["javascript", "python", "html"], "update": "Oct 16, 2022"}
{"username": "Kr1s77", "userurl": "github.com/Kr1s77", "projname": "awesome-python-login-model", "projurl": "github.com/Kr1s77/awesome-python-login-model", "star": "14609", "about": "python模拟登陆一些大型网站，还有一些简单的爬虫，希望对你们有所帮助", "topics": ["python", "twitter-bot", "selenium", "facebook-login", "spiders", "weixinbot", "jingdong", "sina-spider", "github-login", "zhihu-spider", "tuchong", "taobao-spider", "bilibili-login", "lagou-spider", "163mail-login", "douban-spider", "guoke-spider"], "update": "Jul 26, 2022"}
{"username": "xbmc", "userurl": "github.com/xbmc", "projname": "xbmc", "projurl": "github.com/xbmc/xbmc", "star": "14592", "about": "Kodi is an award-winning free and open source home theater/media center software and entertainment hub for digital media. With its beautiful interface and powerful skinning engine, it's available for Android, BSD, Linux, macOS, iOS, tvOS and Windows.", "topics": ["android", "python", "macos", "linux", "c-plus-plus", "ios", "multimedia", "xml", "kodi", "windows-uwp", "media-player", "windows-desktop", "xbmc", "media-center", "hacktoberfest", "home-theater", "entertainment-hub"], "update": "Oct 17, 2022"}
{"username": "imarvinle", "userurl": "github.com/imarvinle", "projname": "awesome-cs-books", "projurl": "github.com/imarvinle/awesome-cs-books", "star": "14463", "about": "经典编程书籍大全，涵盖：计算机系统与网络、系统架构、算法与数据结构、前端开发、后端开发、移动开发、数据库、测试、项目与团队、程序员职业修炼、求职面试等", "topics": ["python", "java", "linux", "javaweb", "cs-books"], "update": "Jun 15, 2022"}
{"username": "ArchiveBox", "userurl": "github.com/ArchiveBox", "projname": "ArchiveBox", "projurl": "github.com/ArchiveBox/ArchiveBox", "star": "14335", "about": "Open source self-hosted web archiving. Takes URLs/browser history/bookmarks/Pocket/Pinboard/etc., saves HTML, JS, PDFs, media, and more...", "topics": ["python", "rss", "backups", "firefox", "pinboard", "youtube-dl", "chromium", "self-hosted", "wget", "pocket", "browser-bookmarks", "warc", "web-archiving", "wayback-machine", "digipres", "singlefile", "headless-browser", "bookmark-archiver", "internet-archiving", "archivebox"], "update": "Sep 14, 2022"}
{"username": "microsoft", "userurl": "github.com/microsoft", "projname": "LightGBM", "projurl": "github.com/microsoft/LightGBM", "star": "14276", "about": "A fast, distributed, high performance gradient boosting (GBT, GBDT, GBRT, GBM or MART) framework based on decision tree algorithms, used for ranking, classification and many other machine learning tasks.", "topics": ["microsoft", "python", "machine-learning", "data-mining", "r", "parallel", "distributed", "kaggle", "gbdt", "gbm", "lightgbm", "gbrt", "decision-trees", "gradient-boosting"], "update": "Oct 17, 2022"}
{"username": "wting", "userurl": "github.com/wting", "projname": "autojump", "projurl": "github.com/wting/autojump", "star": "14260", "about": "A cd command that learns - easily navigate directories from the command line", "topics": ["python", "filesystem", "command-line-tool", "autojump"], "update": "Oct 15, 2022"}
{"username": "microsoft", "userurl": "github.com/microsoft", "projname": "recommenders", "projurl": "github.com/microsoft/recommenders", "star": "14225", "about": "Best Practices on Recommendation Systems", "topics": ["microsoft", "python", "kubernetes", "data-science", "machine-learning", "tutorial", "deep-learning", "azure", "rating", "jupyter-notebook", "artificial-intelligence", "ranking", "recommender", "recommendation-system", "recommendation-engine", "recommendation", "recommendation-algorithm", "operationalization"], "update": "Oct 16, 2022"}
{"username": "mahmoud", "userurl": "github.com/mahmoud", "projname": "awesome-python-applications", "projurl": "github.com/mahmoud/awesome-python-applications", "star": "14008", "about": "Free software that works great, and also happens to be open-source Python.", "topics": ["audio", "game", "python", "productivity", "science", "education", "application", "gui", "video", "graphics"], "update": "Jul 10, 2022"}
{"username": "python", "userurl": "github.com/python", "projname": "mypy", "projurl": "github.com/python/mypy", "star": "13948", "about": "Optional static typing for Python", "topics": ["python", "typechecker", "types", "linter", "typing"], "update": "Oct 17, 2022"}
{"username": "pulumi", "userurl": "github.com/pulumi", "projname": "pulumi", "projurl": "github.com/pulumi/pulumi", "star": "13935", "about": "Pulumi - Universal Infrastructure as Code. Your Cloud, Your Language, Your Way", "topics": ["javascript", "python", "go", "kubernetes", "golang", "aws", "cloud", "typescript", "csharp", "serverless", "fsharp", "dotnet", "azure", "containers", "gcp", "iac", "cloud-computing", "infrastructure-as-code"], "update": "Oct 17, 2022"}
{"username": "twintproject", "userurl": "github.com/twintproject", "projname": "twint", "projurl": "github.com/twintproject/twint", "star": "13905", "about": "An advanced Twitter scraping & OSINT tool written in Python that doesn't use Twitter's API, allowing you to scrape a user's followers, following, Tweets and more while evading most API limitations.", "topics": ["python", "elasticsearch", "kibana", "osint", "twitter", "tweets", "scrape", "twint", "tweep", "scrape-followers", "scrape-likes", "scrape-following"], "update": "May 19, 2022"}
{"username": "Textualize", "userurl": "github.com/Textualize", "projname": "textual", "projurl": "github.com/Textualize/textual", "star": "13900", "about": "Textual is a TUI (Text User Interface) framework for Python inspired by modern web development.", "topics": ["python", "terminal", "tui", "rich"], "update": "Oct 16, 2022"}
{"username": "wangshub", "userurl": "github.com/wangshub", "projname": "wechat_jump_game", "projurl": "github.com/wangshub/wechat_jump_game", "star": "13870", "about": "微信《跳一跳》Python 辅助", "topics": ["python", "adb", "wechat-app"], "update": "Jun 21, 2022"}
{"username": "ansible", "userurl": "github.com/ansible", "projname": "awx", "projurl": "github.com/ansible/awx", "star": "11463", "about": "AWX Project", "topics": ["python", "ansible", "automation", "django", "reactjs", "django-rest-framework", "hacktoberfest", "awx"], "update": "Oct 15, 2022"}
{"username": "davisking", "userurl": "github.com/davisking", "projname": "dlib", "projurl": "github.com/davisking/dlib", "star": "11463", "about": "A toolkit for making real world machine learning and data analysis applications in C++", "topics": ["python", "c-plus-plus", "machine-learning", "computer-vision", "deep-learning", "machine-learning-library", "dlib"], "update": "Oct 9, 2022"}
{"username": "pydantic", "userurl": "github.com/pydantic", "projname": "pydantic", "projurl": "github.com/pydantic/pydantic", "star": "11289", "about": "Data parsing and validation using Python type hints", "topics": ["python", "validation", "parsing", "json-schema", "hints", "python37", "python38", "pydantic", "python39", "python310"], "update": "Oct 16, 2022"}
{"username": "SFTtech", "userurl": "github.com/SFTtech", "projname": "openage", "projurl": "github.com/SFTtech/openage", "star": "11282", "about": "Free (as in freedom) open source clone of the Age of Empires II engine", "topics": ["game", "python", "linux", "c-plus-plus", "qt", "cmake", "opengl", "clone", "game-engine", "cpp", "multiplayer", "engine", "game-development", "entity-component-system", "nyan", "cpp17", "openage", "age-of-empires", "rts-engine"], "update": "Oct 17, 2022"}
{"username": "netbox-community", "userurl": "github.com/netbox-community", "projname": "netbox", "projurl": "github.com/netbox-community/netbox", "star": "11277", "about": "The premiere source of truth powering network automation. Open source under Apache 2. Public demo:", "topics": ["python", "network", "sysadmin", "infrastructure-management", "network-automation", "netbox", "ipam", "dcim", "cabling", "sot"], "update": "Oct 16, 2022"}
{"username": "FavioVazquez", "userurl": "github.com/FavioVazquez", "projname": "ds-cheatsheets", "projurl": "github.com/FavioVazquez/ds-cheatsheets", "star": "11268", "about": "List of Data Science Cheatsheets to rule the world", "topics": ["python", "r", "programming", "spark", "jupyter", "datascience", "cheatsheet"], "update": "Jun 9, 2022"}
{"username": "leon-ai", "userurl": "github.com/leon-ai", "projname": "leon", "projurl": "github.com/leon-ai/leon", "star": "11255", "about": "Leon is your open-source personal assistant.", "topics": ["nodejs", "python", "bot", "text-to-speech", "automation", "privacy", "ai", "offline", "chatbot", "artificial-intelligence", "speech-synthesis", "assistant", "speech-recognition", "personal-assistant", "speech-to-text", "leon", "flite", "voice-assistant", "virtual-assistant", "deepspeech"], "update": "Oct 16, 2022"}
{"username": "allenai", "userurl": "github.com/allenai", "projname": "allennlp", "projurl": "github.com/allenai/allennlp", "star": "11236", "about": "An open-source NLP research library, built on PyTorch.", "topics": ["python", "nlp", "data-science", "natural-language-processing", "deep-learning", "pytorch"], "update": "Oct 12, 2022"}
{"username": "postmanlabs", "userurl": "github.com/postmanlabs", "projname": "httpbin", "projurl": "github.com/postmanlabs/httpbin", "star": "11202", "about": "HTTP Request & Response Service, written in Python + Flask.", "topics": ["python", "testing", "api", "http", "json", "service", "http-server", "httpbin"], "update": "Sep 26, 2022"}
{"username": "beetbox", "userurl": "github.com/beetbox", "projname": "beets", "projurl": "github.com/beetbox/beets", "star": "11188", "about": "music library manager and MusicBrainz tagger", "topics": ["python", "music", "cli", "music-library", "musicbrainz", "hacktoberfest"], "update": "Oct 17, 2022"}
{"username": "microsoft", "userurl": "github.com/microsoft", "projname": "IoT-For-Beginners", "projurl": "github.com/microsoft/IoT-For-Beginners", "star": "11176", "about": "12 Weeks, 24 Lessons, IoT for All!", "topics": ["python", "raspberry-pi", "iot", "rpi", "microcontroller", "cpp", "hacktoberfest", "iot-device", "iot-edge"], "update": "Oct 14, 2022"}
{"username": "getpelican", "userurl": "github.com/getpelican", "projname": "pelican", "projurl": "github.com/getpelican/pelican", "star": "11175", "about": "Static site generator that supports Markdown and reST syntax. Powered by Python.", "topics": ["python", "static-site-generator", "pelican"], "update": "Sep 23, 2022"}
{"username": "wifiphisher", "userurl": "github.com/wifiphisher", "projname": "wifiphisher", "projurl": "github.com/wifiphisher/wifiphisher", "star": "11171", "about": "The Rogue Access Point Framework", "topics": ["python", "security", "attack", "malware", "phishing", "wifi", "rogue", "wifiphisher", "access-point", "redteaming"], "update": "Aug 25, 2022"}
{"username": "nltk", "userurl": "github.com/nltk", "projname": "nltk", "projurl": "github.com/nltk/nltk", "star": "11133", "about": "NLTK Source", "topics": ["python", "nlp", "machine-learning", "natural-language-processing", "nltk"], "update": "Oct 12, 2022"}
{"username": "albumentations-team", "userurl": "github.com/albumentations-team", "projname": "albumentations", "projurl": "github.com/albumentations-team/albumentations", "star": "10985", "about": "Fast image augmentation library and an easy-to-use wrapper around other libraries. Documentation:", "topics": ["python", "machine-learning", "deep-learning", "detection", "image-processing", "image-classification", "segmentation", "object-detection", "image-segmentation", "image-augmentation", "augmentation", "fast-augmentations"], "update": "Oct 17, 2022"}
{"username": "apple", "userurl": "github.com/apple", "projname": "turicreate", "projurl": "github.com/apple/turicreate", "star": "10828", "about": "Turi Create simplifies the development of custom machine learning models.", "topics": ["python", "machine-learning", "deep-learning"], "update": "Nov 29, 2021"}
{"username": "Ciphey", "userurl": "github.com/Ciphey", "projname": "Ciphey", "projurl": "github.com/Ciphey/Ciphey", "star": "10805", "about": "Automatically decrypt encryptions without knowing the key or cipher, decode encodings, and crack hashes", "topics": ["python", "natural-language-processing", "cryptography", "cipher", "cpp", "hacking", "artificial-intelligence", "pentesting", "ctf", "hashes", "encodings", "decryption", "hacktoberfest", "ctf-tools", "encryptions", "deep-neural-network", "cyberchef-magic"], "update": "Oct 1, 2022"}
{"username": "ctgk", "userurl": "github.com/ctgk", "projname": "PRML", "projurl": "github.com/ctgk/PRML", "star": "10730", "about": "PRML algorithms implemented in Python", "topics": ["python", "jupyter", "notebook", "prml"], "update": "May 14, 2022"}
{"username": "PySimpleGUI", "userurl": "github.com/PySimpleGUI", "projname": "PySimpleGUI", "projurl": "github.com/PySimpleGUI/PySimpleGUI", "star": "10696", "about": "Launched in 2018. It's 2022 and PySimpleGUI is actively developed & supported. Create complex windows simply. Supports tkinter, Qt, WxPython, Remi (in browser). Create GUI applications trivially with a full set of widgets. Multi-Window applications are also simple. 3.4 to 3.11 supported. 325+ Demo programs & Cookbook for rapid start. Extensive documentation.  Examples for Machine Learning(OpenCV Integration,  Chatterbot), Rainmeter-like Desktop Widgets, Matplotlib + Pyplot integration, add GUI to command line scripts, PDF & Image Viewer. For both beginning and advanced programmers. docs -  PySimpleGUI.org GitHub - PySimpleGUI.com. The Minecraft of GUIs - simple to complex... does them all.", "topics": ["python", "gui", "qt", "games", "tkinter", "remi", "user-interface", "gui-framework", "pyside2", "wxpython", "qt-gui", "beginner-friendly", "systemtray", "datavisualization", "tkinter-gui", "python-gui", "tkinter-python", "gui-programming", "pysimplegui", "gui-window"], "update": "Oct 16, 2022"}
{"username": "dbcli", "userurl": "github.com/dbcli", "projname": "pgcli", "projurl": "github.com/dbcli/pgcli", "star": "10683", "about": "Postgres CLI with autocompletion and syntax highlighting", "topics": ["python", "postgres", "database", "postgresql", "psql"], "update": "Oct 13, 2022"}
